#+TITLE: Journal Entry-  21 Dec 2017
#+AUTHOR: xing wenju
#+IRC: linuxing3 on freenode
#+EMAIL: xingwenju@gmail.com
#+STARTUP: overview

* 新思想深入把握习近平新时代中国特色社会主义思想的丰富内涵

 http://mp.weixin.qq.com/s/op2GV2phHXlstu5Q3wk8Mg

    习近平新时代中国特色社会主义思想从指导思想层面看，主要是十九大报告概括的“八个明
 确”。

 　　一是总任务。明确坚持和发展中国特色社会主义，总任务是实现社会主义现代化和中华
 民族伟大复兴，在全面建成小康社会的基础上，分两步走在本世纪中叶建成富强民主文明和
 谐美丽的社会主义现代化强国。

 　　二是发展方向。明确新时代我国社会主要矛盾是人民日益增长的美好生活需要和不平衡
 不充分的发展之间的矛盾，必须坚持以人民为中心的发展思想，不断促进人的全面发展、全
 体人民共同富裕。

 　　三是总体布局与战略布局。明确中国特色社会主义事业总体布局是“五位一体”、战略布
 局是“四个全面”，强调坚定道路自信、理论自信、制度自信、文化自信。

 　　四是发展动力。明确全面深化改革总目标是完善和发展中国特色社会主义制度、推进国
 家治理体系和治理能力现代化。

 　　五是法治保障。明确全面推进依法治国总目标是建设中国特色社会主义法治体系、建设
 社会主义法治国家。

 　　六是军事保障。明确党在新时代的强军目标是建设一支听党指挥、能打胜仗、作风优良
 的人民军队，把人民军队建设成为世界一流军队。

 　　七是外部条件。明确中国特色大国外交要推动构建新型国际关系，推动构建人类命运共
 同体。

 　　八是政治保证。明确中国特色社会主义最本质的特征是中国共产党领导，中国特色社会
 主义制度的最大优势是中国共产党领导，党是最高政治领导力量，提出新时代党的建设总要
 求，突出政治建设在党的建设中的重要地位。这“八个明确”系统完备、逻辑严密、内在统一。


 　　新时代坚持和发展中国特色社会主义基本方略，是习近平新时代中国特色社会主义思想
 的重要组成部分。围绕贯彻落实习近平新时代中国特色社会主义思想，十九大报告提出了新
 时代坚持和发展中国特色社会主义基本方略，并概括为“十四个坚持”。这“十四个坚持”包括：
 坚持党对一切工作的领导、坚持以人民为中心、坚持全面深化改革、坚持新发展理念、坚持
 人民当家作主、坚持全面依法治国、坚持社会主义核心价值体系、坚持在发展中保障和改善
 民生、坚持人与自然和谐共生、坚持总体国家安全观、坚持党对人民军队的绝对领导、坚持
 “一国两制”和推进祖国统一、坚持推动构建人类命运共同体、坚持全面从严治党。这“十四
 个坚持”，是落实习近平新时代中国特色社会主义思想的实践要求，构成了习近平新时代中
 国特色社会主义思想的重要组成部分。


 　　习近平新时代中国特色社会主义思想中的“八个明确”和基本方略，本质上是完全一致的。
 “八个明确”是指导思想层面的表述，新时代坚持和发展中国特色社会主义基本方略是行动纲
 领层面的表述，是在各项工作中全面准确贯彻落实习近平新时代中国特色社会主义思想的精
 神实质和丰富内涵，两者在核心要义和精神实质上是一致的。“八个明确”和基本方略是一个
 有机整体，相互贯通、相辅相成，但又各有侧重，前者更多系统回答新时代坚持和发展什么
 样的中国特色社会主义，后者更多系统回答新时代怎样坚持和发展中国特色社会主义，两者
 统一于坚持和发展中国特色社会主义这个主题。

* Tenedores de bonos soberanos temen un default selectivo

Caracas.- Los tenedores de bonos soberanos de Venezuela han empezado a
preocuparse por la posibilidad de que el gobierno de Nicolás Maduro ejecute un
default selectivo en el que dejará de pagarles para cumplir con los compromiso
de Petróleos de Venezuela (Pdvsa).

“Hay mucha incertidumbre, y es imposible saber si los cupones perdidos son el
resultado de un impago o de obstáculos en el mecanismo de pago”, dijo a
Bloomberg, Graham Stock, jefe de investigación soberana de mercados emergentes
en Londres en BlueBay Asset Management. “Si se trata de lo primero, entonces
ciertamente podría ser un incumplimiento selectivo”.

Venezuela realizó el último pago de su deuda soberana en septiembre. El gobierno
está ahora retrasado en $700 millones en intereses sobre ocho bonos, seis de los
cuales se consideraron en mora luego de que expiraran sus períodos de gracia.
Mientras que el presidente Nicolás Maduro ha dicho en repetidas ocasiones que la
nación hace honor a su deuda – y que el proceso de pago ha sido afectado por los
bloqueos financieros protagonizadas por los “enemigos capitalistas” – esas
palabras tranquilizadoras han sido menos frecuente en las últimas semanas.

La última vez que los funcionarios dijeron que transfirieron fondos para pagar a
los acreedores fue el 15 de noviembre, por dos bonos que aún no se han recibido
en la cuenta de los tenedores, reseñó el portal Banca y Negocios.

Sin embargo, muchos inversionistas a largo plazo probablemente no venderán sus
tenencias de bonos soberanos hasta que estén seguros de que ya no habrá más
pagos. Según Bank of America, es difícil saber cuándo se tendrá claridad sobre
los planes del gobierno, escribieron estrategas del banco en un informe el 13 de
diciembre.

** Retiran calificación a bonos 2036 y 2026

La agencia Moody’s Investors Service retiró la calificación Caa3 del bono del
Gobierno de Venezuela por $5.000 millones y cupón de 6,5% con vencimiento el 29
de diciembre de 2036.

“Moody’s ha decidido retirar las calificaciones por sus propios motivos
comerciales”, aseguró la agencia en un breve comunicado. Lo que significa que
ese papel ya no tiene ninguna calificación por parte de esa empresa.

Moody’s explica que el retiro de la calificación puede “ocurrir si surgen
circunstancias nuevas y materiales, cuyos efectos impiden un análisis
satisfactorio; si ya no hay datos actualizados razonables disponibles para
permitir la formación de un juicio.”

El bono soberano 2036 debe cancelar por concepto de intereses $162.5 millones el
próximo 29 de diciembre y tiene un período de gracia hasta el 29 de enero
de 2018.

La calificadora ya había rebajado la nota de los bonos de Pdvsa por el retraso
en los pagos en noviembre y en agosto había advertido de la posibilidad de que
Venezuela entrara en un evento de pago.

Por su parte, S&P Global Ratings bajó su calificación del bono Pdvsa 2026 a ‘D’
desde ‘CC’, equivalente a default, informó la agencia en una nota.

“Pdvsa no ha cumplido con el pago del cupón en sus papeles 2026 dentro del
calendario de 30 días de período de gracia (o al menos los bonistas no habían
recibido los fondos para esa fecha), constituyendo un evento de incumplimiento,
según nuestra metodología”, indicó S&P.

Destacan que “desde octubre de 2017, Pdvsa utilizó su período de gracia para el
pago de intereses en un esfuerzo por reunir suficientes dólares para cumplir con
los vencimientos de su deuda. Dadas las sanciones que pesan sobre Pdvsa y su
posición de liquidez ya presionada, dudamos de la capacidad de la compañía para
pagar el resto de los vencimientos de su deuda dentro del período de gracia”.

Pdvsa anunció el jueves el pago del bono 2026 y otros tres por un total de $539
millones. Ya S&P ha declarado en default otros bonos de la petrolera y la
asociación Isda también declaró un evento de pago el pasado mes.

El período de gracia de los cupones del Pdvsa 2026 venció el pasado viernes 15
de diciembre y su pago es por $135 millones. El lunes 18 vencieron los periodos
de gracia de otros tres bonos de la petrolera estatal: 2024, 2021 y 2035.

El valor de los bonos de Pdvsa abría la jornada de este martes con un alza
promedio de 0,4%, ampliando la brecha con respecto a los soberanos.
