** Embajada estadounidense pide a Maduro liberar a los "presos políticos"

[[http://www.eluniversal.com/noticias/politica/embajada-estadounidense-pide-maduro-liberar-los-presos-politicos_682038][Embajada estadounidense pide a Maduro liberar a los "presos políticos"]]

.- La embajada de Estados Unidos en Caracas solicitó hoy al “régimen” del
presidente venezolano, Nicolás Maduro, que libere a los 268 “presos políticos”
opositores en el marco de las celebraciones navideñas.“Durante esta temporada de
fiestas, nuestros pensamientos están con los 268 prisioneros políticos detenidos
en Venezuela. Hacemos un llamado al régimen de Maduro para que respeten sus
derechos humanos. Libérenlos en estas fiestas”, fue la solicitud de la embajada
a través del Twitter @usembassyve, precisó DPA.El mensaje vino acompañado de la
etiqueta #StandUp4HumanRights o “levántate por los derechos humanos”.De momento
no se ha producido ninguna respuesta oficial por parte del Gobierno venezolano,
que siempre ha rechazado enfáticamente que existan presos de consciencia en su
país y más bien atribuye las detenciones al carácter “violento” y “golpista” de
los planes de la oposición para derrocar a Maduro.Estados Unidos y Venezuela
mantienen unas tirantes relaciones bilaterales por las frecuentes críticas de
Washington a las supuestas violaciones de los derechos humanos en el país
sudamericano, que por su lado ha fustigado las políticas supuestamente
injerencistas y belicistas de la nación norteamericana.Washington y Caracas
carecen de relaciones a nivel de embajador desde 2008, cuando el entonces
presidente venezolano Hugo Chávez denunció que Estados Unidos conspiraba para
derrocar a gobiernos de América Latina.

** Ignorar informe de la OEA en Honduras es antecedente peligroso antecedente

[[http://www.eluniversal.com/noticias/internacional/ignorar-informe-oea-honduras-antecedente-peligroso-antecedente_682041][Ignorar informe de la OEA en Honduras es antecedente peligroso antecedente]]

-  La secretaría general de la OEA cree que desconocer los informes de su misión electoral en Honduras sienta un “antecedente peligroso” de cara a un 2018 lleno de comicios en el continente americano y asegura que las irregularidades han afectado “seguramente” el resultado de los comicios presidenciales.Así lo indicaron este 22 de diciembre fuentes de la propia secretaría general de la Organización de Estados Americanos (OEA) a DPA.Estados Unidos avaló hoy al presidente Juan Orlando Hernández como vencedor de los comicios del 26 de noviembre pese a las denuncias de fraude de la oposición y a la petición del secretario general de la OEA, Luis Almagro, de nuevas elecciones por las irregularidades que constató la misión electoral de la organización.Antes que Estados Unidos fueron Colombia y México los que felicitaron al conservador Hernández.“Nuestra posición solamente puede y debe reflejar las conclusiones de la Misión de Observación Electoral de la Organización, que ha señalado claramente la imposibilidad de determinar un ganador de estos comicios”, dijeron las fuentes.“Esto es así producto del cúmulo de irregularidades y deficiencias graves denunciadas, que seguramente han afectado el resultado electoral, lo cual no permite reconocer la proclamación formulada por el Tribunal Supremo Electoral hondureño”, añadieron.En el año que está a punto de comenzar hay programadas elecciones presidenciales en Colombia, México, Brasil, Costa Rica, Paraguay y Venezuela, además de elecciones regionales y municipales en Perú.Almagro no emitirá comentarios sobre los reconocimientos de los países a la proclamación de Hernández como presidente porque estos son “soberanos” para tomar unas decisiones que no le corresponde analizar a él, añadieron las fuentes de la secretaría general de la OEA.

** "El Puma" habló con Ricardo Montaner pero sigue en cuidados intensivos

[[http://www.eluniversal.com/noticias/musica/puma-hablo-con-ricardo-montaner-pero-sigue-cuidados-intensivos_682025]["El Puma" habló con Ricardo Montaner pero sigue en cuidados intensivos]]

.- El cantante venezolano José Luis Rodríguez “El Puma” ha comenzado a hablar
aunque aún permanece en cuidados intensivos, cinco días después de un doble
trasplante de pulmón en Miami.Así lo informaron a Efe fuentes cercanas al
artista de 74 años, quienes agregaron que “se sigue recuperando
satisfactoriamente”, aunque declinaron dar más detalles porque así lo han pedido
la esposa de “El Puma”, Carolina Pérez, y su hija menor, Génesis Rodríguez.En
Twitter el cantautor argentino-venezolano Ricardo Montaner contó que había
conversado brevemente con Rodríguez por teléfono, lo que da a entender que le
han retirado ya el tubo endotraqueal que le ayudaba a respirar.“¿Adivinen quien
me acaba de llamar por teléfono?”, escribió Montaner. “El mismísimo PUMA. Ya me
empezó a hablar de volver a donde pertenece... a la música”.Montaner, quien
produjo , el primer disco de Rodríguez en ocho años, agregó. “Le dije que
‘tranquilo chamo, estamos de vacaciones’. Gloria a Dios por sus milagros y por
dejarme ser testigo de ellos”.“El Puma” fue operado en la madrugada del 17 de
diciembre en el hospital Jackson Memorial de Miami, para recibir un doble
trasplante de pulmón.Este el único procedimiento que puede garantizar una
recuperación a los pacientes de fibrosis pulmomar, una enfermedad que obligaba
al cantante de  a mantenerse dependiente de una bombona de oxígeno.“José Luis
les agradece infinitamente su amor, su apoyo y sus buenos deseos, así como el
entendimiento de este proceso, como algo discreto y muy personal”, dijeron su
esposa e hija menor en el único comentario oficial desde la intervención.En las
redes sociales sus hijas mayores, Liliana y Lilibeth Rodríguez Morillo, y su
nieta Galilea reconocieron que no lo han visto, pero le expresaron sus deseos de
una rápida y completa recuperación.

** GNB movilizada ante fallas de gasolina y gas en Barinas

[[http://www.eluniversal.com/noticias/venezuela/gnb-movilizada-ante-fallas-gasolina-gas-barinas_682033][GNB movilizada ante fallas de gasolina y gas en Barinas]]

Las fallas de gasolina y gas de uso doméstico sigue siendo un problema para los
ciudadanos de Barinas, que deben someterse a colas desde muy tempranas horas con
el fin de obtener el producto para unos días.Desde el pasado jueves la presencia
de los funcionarios de orden interno de la Guardia Nacional Bolivariana (GNB) en
la entidad ha sido con mayor intensidad en gasolineras, aplicando un dispositivo
de seguridad especial para garantizar la mejor distribución posible de este
producto y del gas, ambos con gran demanda en estos días en Barinas.Incluso, los
funcionarios se encontraban este viernes en la tarde en la redoma que sirve de
entrada y salida a Barinas, portando equipos antimotines que son utilizados
durante las protestas.Por las fallas de gasolina en Barinas no ha habido
acciones de calles que causen desorden público, sin embargo, los ciudadanos que
reclaman la eficiente distribución de gas han ejercido presión cerrando vías.En
Barinas las colas por gasolina reúnen a quienes residen en la entidad y también
a una gran cantidad de personas que aprovechan la fecha navideña para viajar,
tocándoles recargar sus tanques en este punto de su recorrido.

** 7 días en 2 minutos

[[http://www.eluniversal.com/videos/politica/dias-minutos_546529][7 días en 2 minutos]]



** GNB incauta 200 panelas de droga en el estado Zulia

[[http://www.eluniversal.com/noticias/venezuela/gnb-incauta-200-panelas-droga-estado-zulia_682040][GNB incauta 200 panelas de droga en el estado Zulia]]

La Guardia Nacional Bolivariana (GNB) incautó 200 panelas de droga en el
municipio Baralt del estado Zulia, según informó este viernes el comandante de
la Zona Operativa de Defensa Integral (Zodi) en Zulia, Javier Benchimol.En
declaraciones transmitidas por Venezolana de Televisión, indicó que durante el
procedimiento fueron detenidos dos ciudadanos. Por su parte, el presidente de la
Oficina Nacional Antidrogas (ONA), José Castillo, precisó que en esa entidad se
han incautado, durante este año, 25 toneladas de drogas, reseñó AVN."Este estado
ocupa el primer lugar en incautación a nivel nacional con un 61% del total
general de droga incautada", aseguró Castillo.

** Presidente Maduro envió mensaje navideño al pueblo venezolano

[[http://www.eluniversal.com/noticias/politica/presidente-maduro-envio-mensaje-navideno-pueblo-venezolano_682039][Presidente Maduro envió mensaje navideño al pueblo venezolano]]

El presidente de la República, Nicolás Maduro, envió este viernes un mensaje de
amor al pueblo venezolano con motivo de la celebración de la navidad y el año
nuevo."Les deseo a todos hermanos y hermanas del alma una feliz navidad y un
prospero y venturoso año 2018. ¡Feliz navidad pueblo amado!", expresó el
mandatario nacional.A través de un video publicado en su cuenta en twitter,
destacó que el año 2017 trajo la victoria de la paz ante las adversidades que
pretendieron socavar el camino democrático y revolucionario de Venezuela, reseñó
AVN."Tantas batallas en este 2017, con la firmeza afincada en el amor derrotamos
la oscuridad y la tristeza. Fue la victoria de la paz. Fue la victoria de la
vida", manifestó.Agregó que la esperanza ha sido renovada en el pueblo para
nuevas victorias y el despegue hacia la consolidación de Venezuela como una
potencia en el 2018.Asimismo, destacó el carácter y valentía del pueblo ante las
dificultades y refirió a las palabras del líder de la Revolución Bolivariana,
Hugo Chávez."Si yo pudiera hacer de mi corazón una condecoración, se la pondría
en el pecho al pueblo de Venezuela", expresó.Aquí les dejamos el video:

** 
			
		

[[http://www.eluniversal.com/][
			
		]]



** Elector explica su situación tras ser reubicado en otro centro de votación

[[http://www.eluniversal.com/audios/politica/elector-explica-situacion-tras-ser-reubicado-otro-centro-votacion_536545][Elector explica su situación tras ser reubicado en otro centro de votación]]



** Declaración del equipo de asesores de la oposición en el proceso de diálogo

[[http://www.eluniversal.com/noticias/politica/declaracion-del-equipo-asesores-oposicion-proceso-dialogo_682037][Declaración del equipo de asesores de la oposición en el proceso de diálogo]]

En pleno proceso de negociaciones que se lleva a cabo en República Dominicana
con facilitación internacional, la ANC ilegítima intenta obstruir ese esfuerzo
al pretender eliminar a los Distritos Metropolitanos de Apure y Caracas, y al
desconocer los derechos políticos de los venezolanos.Esa ANC ilegítima no tiene
competencias para tomar semejante medida y menos de espaldas al pueblo. La
Constitución Nacional vigente privilegia la participación ciudadana en la
decisión de conformar Distritos Metropolitanos que hagan más eficientes los
Gobiernos de Alcaldías vecinas y con intereses comunes. Además, la organización
de estos Distritos corresponde exclusivamente a la Asamblea Nacional mediante
Ley especial. De esta forma la ANC ilegítima pretende soslayar la voluntad del
pueblo que desde el imperio de la Constitución de 1999 ha elegido a sus Alcaldes
y Cabildos Metropolitanos, y una vez más ha usurpado funciones que la
Constitución reserva a la Asamblea Nacional.En el caso de Caracas la situación
es aún más delicada pues la supresión del Distrito Metropolitano deja sin efecto
el artículo 18 de la Constitución que consagra ese Distrito como Unidad Político
Territorial que concrete dos niveles de gobierno en la Capital. La ANC, incluso
si fuera legítima, no puede derogar ni suprimir mandatos de la Constitución, y
su función se limita a redactar una nuevaConstitución para la transformación del
Estado y someterla a Referéndum popular.Los habitantes de los Municipios
afectados por esta medida tienen a su disposición dos herramientas poderosas
previstas en el artículo 70 de la Constitución, los Cabildos Abiertos y las
Asambleas Ciudadanas, cuyas decisiones son incluso vinculantes por mandato de
dicho artículo. Instamos a los Alcaldes, Concejales y líderes vecinales a tomar
esta iniciativa para que el pueblo se exprese y se defienda.Como otra violación
a los derechos constitucionales de los venezolanos, la ilegítima ANC pretende
anular a los partidos políticos que no presentaron candidatos en las últimas
elecciones municipales, algo que sólo las dictaduras más primitivas tienen en su
repertorio de violaciones del Estado de Derecho. El gobierno muestra con ello el
futuro que quiere para el país: un régimen de partido único gobernando con la
manipulación y explotación de las necesidades de la gente.Mientras tanto el país
se encuentra en una situación crítica. La salud, la alimentación, el transporte,
la pérdida del empleo formal y del poder de adquisitivo del salario, la inmensa
miseria y la asfixia del futuro, le doblan la espalda a todo el pueblo y en
especial a los sectores más vulnerables, que son hoy la mayoría del país. La
responsabilidad es de quien gobierna, pero en lugar de aceptar las salidas
negociadas para enfrentar la crisis, ahora pretende suprimir los derechos de los
venezolanos y dirigir el país hacia una mayor ruina, con tal de permanecer en el
poder contra la voluntad mayoritaria.Las acciones que intenta ejercer la espuria
“constituyente”;, creyendo que puede eliminar la Constitución Nacional vigente,
son inválidas e ilegales, sus actos son nulos de nulidad absoluta, y no son ni
aceptadas ni reconocidas por el pueblo venezolano.Exigimos respeto a la
Constitución, respeto a los ciudadanos, respeto al proceso de negociación con
facilitación internacional y medidas urgentes para sacar al país de este estado
de agonía.

** Más de 550.000 venezolanos residen en Colombia

[[http://www.eluniversal.com/noticias/venezuela/mas-550000-venezolanos-residen-colombia_682036][Más de 550.000 venezolanos residen en Colombia]]

.- Más de 550.000 venezolanos residen en Colombia y en las últimas semanas han
aumentado en 7 % las entradas y salidas de nacionales y extranjeros por los
siete puntos fronterizos entre ambos países, informó hoy el departamento de
Migración negranadino."Hoy podemos decir que más de 550.000 venezolanos están
radicados en nuestro país y son personas que están buscando un mejor futuro,
algunos están cumpliendo con la norma migratoria para estar y otros no lo están
haciendo", afirmó el director general de Migración Colombia, Christian Krüger,
en declaraciones difundidas por su despacho, reseñó Efe.El funcionario anunció
además que han puesto en marcha planes de contingencia para atender los
movimientos migratorios en esta época de Navidad y Año Nuevo.Krüger informó de
un "incremento cercano al 7 %" en el movimiento migratorio desde Venezuela, que,
aseguró, equivale a "un promedio de 2.000 personas diarias más" que entran y
salen del país.Migración detalló que la cifra de entradas de venezolanos por el
Puente Internacional Simón Bolívar, en el departamento de Norte de Santander
(noreste), subió de 35.000 a 37.000, mientras que las salidas subieron de 33.000
a 35.000 personas por día.El funcionario destacó como positivas las medidas
adoptadas por Colombia, como el Permiso Especial de Permanencia (PEP), el cual
benefició a 69.000 venezolanos que han podido abrir una cuenta bancaria y
afiliarse al sistema de seguridad social, y la Tarjeta de Movilidad Fronteriza
(TMF), para quienes transitan por las zonas limítrofes.Según Krüger, hay 1,2
millones de personas están registradas con la TMF.Colombia y Venezuela comparten
2.219 kilómetros de frontera, considerada una de las más activas de América
Latina y donde operan grupos de delincuencia común, guerrillas, bandas
criminales y contrabandistas.

** La Semana de la Moda de París volvió a deslumbrar

[[http://www.eluniversal.com/galerias/estilo-vida/semana-moda-paris-volvio-deslumbrar_4546][La Semana de la Moda de París volvió a deslumbrar]]



** Santa Claus entregó ropa y juguetes a niños en 25 rutas de la Gran Caracas

[[http://www.eluniversal.com/galerias/caracas/santa-claus-entrego-ropa-juguetes-ninos-rutas-gran-caracas_4557][Santa Claus entregó ropa y juguetes a niños en 25 rutas de la Gran Caracas]]



** Conozca "el panal" moneda comunal paralela diseñada en el 23 de Enero

[[http://www.eluniversal.com/galerias/economia/conozca-panal-moneda-comunal-paralela-disenada-enero_4558][Conozca "el panal" moneda comunal paralela diseñada en el 23 de Enero]]



** Largas colas en algunos colegios al arrancar las elecciones catalanas

[[http://www.eluniversal.com/videos/internacional/largas-colas-algunos-colegios-arrancar-las-elecciones-catalanas_546259][Largas colas en algunos colegios al arrancar las elecciones catalanas]]



** Jovencita de 15 años lideró asesinato de dos militares en Sabana Grande

[[http://www.eluniversal.com/noticias/sucesos/jovencita-anos-lidero-asesinato-dos-militares-sabana-grande_644593][Jovencita de 15 años lideró asesinato de dos militares en Sabana Grande]]

Una adolescente de 15 años fue la primera detenida por el doble homicidio de los
funcionarios del Ejército: Yohan Borrero, de 25 años, y Andrés Ortiz, de 23, la
madrugada del domingo en el bulevar de Sabana Grande. Con ella estaba un niño de
10 años cuando los capturaron.La muchacha lideraba el grupo de niños y
adolescentes que esa madrugada atacó a los efectivos a cuchilladas, luego de
haberle arrebatado el bolso a uno de ellos. Eso dijeron funcionarios
policiales.Tras su detención, acusó al resto de los jovencitos que estaban con
ella, y los funcionarios lograron apresar a cuatro más. Se trata de niños con
edades comprendidas entre 6 y 10 años.De acuerdo con la investigación del hecho,
eran unos 12 niños y adolescentes que estaban distribuidos en dos grupos.Dos le
arrebataron el bolso a uno de los militares cuando salieron de la tasca
restaurante El Colosseo a fumar.El resto de los atacantes estaba ubicado en la
esquina Pascual Navarro del bulevar, que conduce hacia la avenida Solano. Los
militares corrieron detrás de los niños con la intención de recuperar el bolso,
y allí fueron detenidos por la banda completa.Con cuchillos en mano se encimaron
a los funcionarios y los apuñalaron con saña, aupados por la líder
quinceañera. El sargento primero Yohan Borrero recibió nueve, y una de ellas en
el cuello que lo dejó muerto en medio del bulevar.El sargento segundo Andrés
Ortiz se desplomó en la avenida por las heridas. Una puñalada en el abdomen lo
neutralizó.Los atacantes huyeron del lugar y se llevaron el bolso.Ambos
militares estaban con dos compañeros en el local nocturno, quienes fueron
avisados del hecho minutos después.Familiares de ambos fallecidos estaban en la
morgue de Bello Monte la mañana de ayer. Los deudos de Borrero dijeron que era
oriundo del estado Portuguesa, y formaba parte del Batallón Bolívar en Fuerte
Tiuna desde al año 2008.El otro funcionario tenía siete días en Caracas en el
mismo batallón. Era de Barcelona, pero lo trasladaron a la capital porque estaba
de curso."En este país no hay valores, las familias se acabaron, no entiendo
cómo unos niños hacen esto, y cómo hay padres que olvidan a sus hijos y los
lanzan a las calles a causar daños", dijo Yuilimar Borrero, hermana del sargento
primero.Le preocupa como abogada que esos niños menores de 12 años no serán
condenados por el delito que cometieron y que pronto saldrán a la calle "porque
no hay ley que los castigue como debería ser".

** Maduro analiza cerrar vías de comunicación con islas del Caribe

[[http://www.eluniversal.com/videos/politica/maduro-analiza-cerrar-vias-comunicacion-con-islas-del-caribe_546082][Maduro analiza cerrar vías de comunicación con islas del Caribe]]



** Más de un millón de temporadistas retornarán por La Bandera

[[http://www.eluniversal.com/noticias/caracas/mas-millon-temporadistas-retornaran-por-bandera_574][Más de un millón de temporadistas retornarán por La Bandera]]

Tras el asueto navideño, se espera para este fin de semana el retorno de más de
un millón de temporadistas por el terminal La Bandera, ubicado en Caracas,
informó el presidente del Instituto Autónomo de Seguridad Ciudadana y Transporte
(Insetra), Robinson Navarro."Esperamos que este fin de semana retornen al menos
un millón de personas, ya que batimos récord este año, pues salieron más de
1.600.000 personas a los diferentes destinos del país", declaró el funcionario a
Radio Nacional de Venezuela.Indicó que 80 funcionarios de la Policía de Caracas,
60 de la Policía Nacional Bolivariana y 72 efectivos de la Guardia Nacional
Bolivariana (GNB) están prestos para brindar resguardo y protección a los
usuarios de la central de transporte terrestre, reseñó AVN.Asimismo, recordó que
a partir del lunes se retomará el precio normal del pasaje, ajustado con un
recargo de 25 % como bono por las festividades decembrinas, según Gaceta Oficial
N 6.172."El convenio que hemos realizado con los transportistas está en vigencia
hasta el 3 de enero y luego tendrán que cobrar nuevamente su pasaje normal sin
el 25 % de recargo", enfatizó.Hasta el pasado miércoles se habían movilizado
1.288.042 pasajeros desde el terminal capitalino y se tiene previsto trasladar
400.000 más hasta el próximo 6 de enero, para lo que se han dispuesto 37.476
unidades de autobuses.

** Gobierno decreta 1 de febrero como "día no laborable"

[[http://www.eluniversal.com/noticias/politica/gobierno-decreta-febrero-como-dia-laborable_637365][Gobierno
decreta 1 de febrero como "día no laborable"]]

El Ejecutivo Nacional decretó el próximo miércoles 1 de febrero como “día  de
júbilo, no laborable”. el presidente de la República Nicolás Maduro durante la
transmisión de su programa número 78 de "Los Domingos con Maduro".Desde las
instalaciones de la empresa Siderúrgica del Orinoco (Sidor), en el estado
Bolívar, el primer mandatario nacional anunció que la decisión será publicada en
la Gaceta Oficial que circulará este lunes 30 de enero.En relación a esto,

** Estos son los resultados del Clásico Mundial de Beisbol

[[http://www.eluniversal.com/noticias/clasico-mundial/estos-son-los-resultados-del-clasico-mundial-beisbol_642685][Estos
son los resultados del Clásico Mundial de Beisbol]]

.- La selección de Estados Unidos le puso punto final a la cuarta edición del
Clásico Mundial de Beisbol con una victoria 8-0 a la selección de Puerto Rico y
su primer campeonato en el certamen. Los dirigidos por Jim Leyland mostraron
bateo oportuno, buena defensa y una excelente labor monticular para blanquear a
la única novena invicta del torneo y amarrar a la ofensiva más productiva de
todo el Clásico.Un cuadrangular de dos carreras de Ian Kinsler e imparables
productores de Andrew McCutchen, Giancarlo Stanton, Brandon Crawford y Christian
Yelich, fueron el principal apoyo para el lanzador Marcus Stroman que lanzó una
joya de seis innings donde permitió un imparable y abanicó a tres rivales para
quedarse con la victoria y el premio al Jugador Más Valioso (MVP) del
torneo.Lamentablemente para Puerto Rico por segundo certamen consecutivo se
quedan a las puertas de un campeonato, tras caer derrotar en 2013 ante República
Dominicana, también por blanqueo.Al finalizar el compromiso la organización WBC
anunció el equipo ideal del Clásico: en la receptoría el electo fue Yadier
Molina (Puerto Rico), en la primera base Eric Hosmer (Estados Unidos), en la
segunda base Javier Báez (Puerto Rico), en el campo corto Francisco Lindor
(Puerto Rico), Carlos Correa (Puerto Rico) en la tercera base. En los jardines
fueron electos Wladimir Balentien (Holanda), Christian Yelich (Estados Unidos) y
Gregory Polanco (República Dominicana), como bateador designado Carlos Belran
(Puerto Rico). Mientras que los lanzadores fueron: Kodai Senga (Japón), Josh
Zeid (Israel) y Marcus Stroman (Estados Unidos).FinalEstados Unidos 8-0 Puerto
RicoG: Marcus Stroman (1-0) | P: Seth Lugo (0-1)Semifinal 2Estados Unidos 2-1
JapónG: Sam Dyson (1-0) | P: Kodai Senga (0-1) | S: Luke Gregerson (1)Semifinal
1Puerto Rico 4-3 Holanda (11 innings)G: Edwin Díaz (1-0) | P: Loek Van Mil
(0-1)Grupo F (Segunda Ronda)Estados Unidos 6-3 República DominicanaG: Danny
Duffy (1-0) | P: Ervin Santana (0-1) | S: Luke Gregerson (2)Grupo F (Segunda
Ronda)Puerto Rico 13-2 VenezuelaG: José De León (1-0) | P: Martín Pérez
(0-1)Grupo F (Segunda Ronda)Puerto Rico 6-5 Estados UnidosG: Seth Lugo (1-0) |
P: Marcus Stroman (0-1) | S: Dayan Díaz (2)Grupo F (Segunda Ronda)República
Dominicana 3-0 VenezuelaG: Fernando Abad (1-0) | P: Jhoulys Chacín (0-1) | S:
Jeurys Familia (1)Grupo F (Segunda Ronda)Estados Unidos 4-2 VenezuelaG: Pat
Neshek (1-0) | P: Héctor Rondón (0-1) | S: Luke Gregerson (1)Grupo E (Segunda
Ronda)Japón 8-3 IsraelG: Yoshihisa Hirano (1-0) | P: Dylan Axelrod (0-1)Grupo E
(Segunda Ronda)Holanda 14-1 Cuba (7 innings)G: Diegomar Markwell (1-0) | P:
Lázaro Blanco (0-1)Grupo F (Segunda Ronda)Puerto Rico 3-1 República DominicanaG:
Héctor Santiago  (1-0) | P: Carlos Martínez (0-1) | S: Edwin Díaz (1)Grupo
E (Segunda Ronda)Japón 8-5 CubaG: Ryo Akiyoshi (1-0) | P: Miguel Lahera (0-1) |
S: Kazuhisa Makita (1)Grupo D (Juego de Desempate)Venezuela 4-3 ItaliaG: José
Alvarado (1-0) | P: Mike DeMark (0-1) | S: Francisco Rodríguez (1)Grupo E
(Segunda Ronda)Holanda 12-2 Israel (8 innings)G: Jair Jurrjens (1-0) | P: Corey
Baker (0-1)Grupo DMéxico 11-9 VenezuelaG: Luis Mendoza (1-0) | P: Yusmeiro Petit
(0-1) | S: Roberto Osuna (1)Grupo CEstados Unidos 8-0 CanadáG: Danny Duffy
(1-0) | P: Ryan Dempster&NegativeThinSpace; (0-2)Grupo DPuerto Rico 9-3 ItaliaG:
José Berríos (1-0) | P: Luis Lugo&NegativeThinSpace; (0-1)Grupo CRepública
Dominicana 10-3 Colombia (11 innings)G: Enny Romero (1-0) | P: William
Cuevas&NegativeThinSpace; (0-1)Grupo E (Segunda Ronda)Israel 4-1 CubaG: Zack
Thornton (1-0) | P: Yoennis Yera (0-1) | S: Josh Zeid (1)Grupo DPuerto Rico 9-4
MéxicoG: Jorge López (1-0) | P: Miguel González (0-1)Grupo CRepública Dominicana
7-5 Estados UnidosG: Alex Colomé (1-0) | P: Andrew Miller (0-1) | S: Jeurys
Familia (1)Grupo DVenezuela 11-10 Italia (10 innings)G: Francisco Rodríguez
(1-0) | P: Trey Nielsen (0-1) | S: José Castillo (1)Grupo CColombia 4-1 CanadáG:
Julio Teherán (1-0) | P: Ryan Kellogg (0-1) | S: Dayan Díaz (1)Grupo DPuerto
Rico 11-0 Venezuela (7 innings)G: Seth Lugo (1-0) | P: Félix Hernández
(0-1)Grupo CEstados Unidos 3-2 Colombia (10 innings)G: Tyler
Clippard&NegativeThinSpace; (1-0) | P: Guillermo Moscoso (0-1)Grupo BJapón 7-1
ChinaG: Shota Takeda&NegativeThinSpace; (1-0) | P: Quan Gan (0-1)Grupo BCuba 4-3
AustraliaG: Vladimir Garcia (1-0) | P: Lachlan Wells (0-1) | S: Miguel Lahera
(1)Grupo DItalia 10-9 MéxicoG: Jordan Romano (1-0) | P: Roberto Osuna (0-1)Grupo
CRepública Dominicana 9-2 CanadáG: Carlos Martínez (1-0) | P: Ryan Dempster
(0-1)Grupo ACorea del Sur 11-8 China Taipéi (10 innings)G: Seung Hwan Oh (1-0) |
P: Hung-Wen Chen (0-2)Grupo BAustralia 11-0 China (7 innings)G:Travis Blackley
(1-0) | P: Kwon Ju (0-0)Grupo AIsrael 4-2 HolandaG: Jason Marquis (1-0) | P: Rob
Cordemans (0-1) | S: Josh Zeid (1)Grupo BJapón 4-1 AustraliaG: Kodai Senga
(1-0) | P: Matt Williams (0-1) | S: Kazuhisa Makita (1)Grupo AHolanda 6-5 China
TaipéiG: Shairon Martis (1-0) | P: Hung-Wen Chen (0-1)Grupo BCuba 6-0 ChinaG:
Vladimir Baños (1-0) | P: Xia Luo (0-1)Grupo BJapón 11-6
CubaG: Ayumu Ishikawa (1-0) | P: Yoennis Yera&NegativeThinSpace; (0-1)Grupo
AHolanda 5-0 Corea del SurG: Rick van den Hurk (1-0) |
P: Kyu Min Woo&NegativeThinSpace; (0-1)Grupo AIsrael
15-7 China TaipéiG: Corey Baker (1-0) | P: Chun-Lin Kuo (0-1)Grupo AIsrael 2-1
Corea del SurG: Josh Zeid (1-0) | P: Chang-Yong Lim (0-1)

** Reconocer el aspecto de una yuca amarga puede salvar la vida

[[http://www.eluniversal.com/noticias/estilo-vida/reconocer-aspecto-una-yuca-amarga-puede-salvar-vida_636802][Reconocer
el aspecto de una yuca amarga puede salvar la vida]]

El sábado pasado falleció un niño de cinco años presuntamente luego de consumir
yuca amarga. El deceso ocurrió en Anzoátegui, entidad donde ha ocurrido la misma
situación durante los últimos meses con otros dos infantes.El doctor Norman
Cutt, toxicólogo clínico y especialista en Respuesta y Control de Emergencias
del Centro Médico Docente La Trinidad, explica que es importante reconocer la
yuca dulce de la amarga pues esta última puede provocar la muerte sobre todo en
los más pequeños del hogar.Cutt, también presidente de la Sociedad Venezolana de
Toxicología Clínica, indicó que el consumo de yuca amarga genera consecuencias a
nivel del torrente sanguíneo; afecta el aparato circulatorio y compromete el
sistema cardiovascular.Comenta que los síntomas están caracterizados por
trastornos gastrointestinales como náuseas y vómitos y, así mismo, por
trastornos neurológicos como mareos y pérdida del conocimiento.“Se van agravando
hasta ocasionar la muerte. Mientras más inmaduro sea el sistema gastrointestinal
más severos son los síntomas. Por este motivo la mayor parte de los decesos han
ocurrido en niños”, puntualizó el doctor.Signos como color azul violáceo en las
orejas, palmas de las manos, uñas, labios o conjuntivas son motivo de alarma
para acudir al médico.Explica que el tratamiento debe comenzar en el hogar. Lo
primero que se debe tener en cuenta es no detener el vómito ya que ésta es una
manera de defensa que tiene el organismo. Posteriormente, se tiene que acudir de
manera inmediata al hospital o al ambulatorio más cercano.Cutt también precisa
que el paciente también puede usar carbón activado tomando una dosis de
1grm/kg/peso disuelto en agua vía oral junto al purgante manitol al 18% tomando
una dosis de 1ml/kg/peso también vía oral. Por otro lado, el experto afirma que
en la Sociedad Venezolana de Toxicología Clínica tienen un subregistro del año
pasado donde se contabilizaron más de 30 casos de intoxicaciones graves.“En el
2016 fallecieron cuatro personas por consumir yuca amarga. Se debe educar a la
población sobre cómo reconocer los alimentos en buen estado”, enfatiza el
toxicólogo.Por su parte, Mariángel Paolini, química de alimentos, resalta que
estos casos se han presentado debido a la escasez de harina y arroz.“Las
personas en su desespero por comer evalúa poco lo que se está llevando a casa.
Las diferencias son pocas por esto los consumidores las pasan por desapercibido.
Por este motivo, también se debe evitar tener cultivos de estos tubérculos en el
hogar”, recomienda Paolini.-El toxicólogo clínico Norman Cutt explica que si
la yuca está dura y de color amarillo no se debe consumir. Hay que desecharla
inmediatamente.-La química de alimentos Mariángel Paolini acota que la cáscara
de la yuca amarga es gruesa y de color rosado.-Ambos expertos coinciden en
que este tipo de tubérculo se debe adquirir en supermercados y no en vendedores
ambulantes.

** Mal clima amenaza la búsqueda del submarino argentino en el Atlántico

[[http://www.eluniversal.com/noticias/internacional/mal-clima-amenaza-busqueda-del-submarino-argentino-atlantico_682026][Mal
clima amenaza la búsqueda del submarino argentino en el Atlántico]]

Fuertes vientos y olas de hasta dos metros y medio de altura amenazarán en los
próximos días la búsqueda del submarino ARA San Juan, desaparecido el pasado 15
de noviembre con 44 tripulantes a bordo a 400 kilómetros de la costa argentina,
donde operan varios buques nacionales y extranjeros. La Armada Argentina informó
en un comunicado que las naves que trabajan en el operativo de búsqueda, el
destructor ARA Sarandí y el ARA Islas Malvinas , destacó Efe.Por su parte, el
oceanográfico Yantar de Rusia, que se incorporó a la zona de operaciones a
principios de diciembre, se encuentra de camino hacia Montevideo (Uruguay) para
concluir ese mismo proceso y reincorporarse cuanto antes a las tareas de
búsqueda. Mientras, la causa que investiga posibles irregularidades en las
reparaciones del ARA San Juan continúa a cargo del juez Sergio Torres,  en torno
a los trabajos de mejora de la flota naval. En este marco, el exalmirante
Marcelo Srur fue destituido de su cargo como jefe de la Armada argentina
mientras se desarrolle la investigación por la desaparición del submarino y
sustituido por el vicealmirante Jose Luis Villán. Hace más de un mes desde que
el submarino ARA San Juan estableció su última comunicación, mientras viajaba
desde el puerto austral de Ushuaia hasta su base en Mar del Plata.

** Caracas para admirar y degustar

[[http://www.eluniversal.com/noticias/guia-turistica/caracas-para-admirar-degustar_681090][Caracas
para admirar y degustar]]

Para quienes no vivimos en Caracas, ir a esta ciudad siempre es una nueva
oportunidad de descubrir algo que nos ayude a  conectar con el sentir
 venezolano. Lo primero que hay que hacer, sin lugar a dudas, es entregarse a la
contemplación del Ávila, hay que ver hacia la montaña a toda hora, desde todas
partes, entre los edificios, desde las avenidas, por las ventanas, sobre los
balcones. Nunca es suficiente para descifrar su magia.La Plaza Francia, en
Altamira,  es perfecta para mirar al Ávila y disfrutar de los jardines de la
plaza, que afortunadamente siempre lucen bien. Al cruzar la avenida Francisco de
Miranda, se puede visitar PDVSA La Estancia, un refugio de naturaleza y
tranquilidad ideal para caminar entre la variada vegetación y descansar en la
grama bajo la sombra de algún árbol. Suelen realizarse exposiciones de arte y
actividades culturales.En la Torre Cavendes, frente La Estancia, se inauguró
recientemente la nueva sede de Páramo Café, una cadena al mejor estilo de las
franquicias americanas de café, pero con concepto venezolano. El lugar es
pequeño,  moderno y  agradable para disfrutar de una bebida fría o caliente
mientras se aprecia el original mural que retrata por completo a Caracas. Se
esmeran en los detalles de la marca ().Si se busca buena gastronomía, solo hay
que moverse hasta Los Palos Grandes, donde se ubica D.O.C. Restaurant, una
interesante propuesta que nació para resaltar los sabores de Venezuela a través
de la Denominación de Origen Controlado. Sorprende descubrir los productos que
trasladan desde distintos lugares del país, de la mano con productores y
emprendedores. Desde la baba del llano hasta los exóticos frutos del Amazonas
tienen cabida en sus creaciones, los platos son de altísimo nivel y el ambiente
muy selecto ().No me iría de la zona sin pasar por la plaza de Los Palos
Grandes, para disfrutar viendo a los niños  bañarse en los chorros que salen del
suelo y luego tomar un café en Provenzal (). Pasaría por el parque Francisco de
Miranda (Parque del Este) solo para pararme frente a los árboles a ver de cerca
a las coloridas guacamayas y disfrutar de su escándalo. Las guacamayas se
convirtieron en un ícono caraqueño.Lejos de pensar que todo se concentra en el
este, hay que trasladarse sin pensarlo hasta el centro de la ciudad. Mi primera
parada sería Artesano, una cafetería a pocos pasos de la Plaza Bolívar, donde se
ratifica que los mejores golfeados siempre serán los de Caracas y sus
alrededores. Es un sitio agradable para conversar entre amigos con un
extraordinario golfeado, un papelón con limón y un café guaro, que tiene un
toque de cocuy y azúcar de naranja. El lugar y sus sabores son adictivos ().En
el C.C Metrocenter,  por la salida de la estación Capitolio, se ubica 
Fragolate, una heladería artesanal que está marcando pauta en la movida que
promueve el consumo de los maravillosos frutos exóticos del Amazonas. Copoazú,
túpiro, manaca y arazá son algunos de los nombres a los que nos iremos
acostumbrando, porque cada día ganan más espacio en nuestra gastronomía. Es toda
una sorpresa probar todos estos sabores en helados ().No me iría del centro sin
ir a la casa natal de Simón Bolívar, para luego  caminar por el boulevard
Panteón hasta el histórico edificio donde reposan sus restos. En la ruta se
puede entrar a la Casa de Estudios de la Historia de Venezuela, una impecable
edificación con un patio donde parece que el tiempo se detiene. Solo hay espacio
para la calma en medio de un bonito jardín donde funciona el Restaurant Casa
Veroes, lleno de sabores criollos ().@eduardomonzn

** Las Toninas del Orinoco

[[http://www.eluniversal.com/noticias/guia-turistica/las-toninas-del-orinoco_681088][Las
Toninas del Orinoco]]

Sin duda alguna la mayoría de los venezolanos conocemos los llanos, creo que
todos hemos cruzado así sea por una pequeña porción de esta vasta región
biogeográfica que lleva por nombre los llanos y que representan uno de los
ecosistemas más productivos del mundo. Los llanos de Venezuela cuentan con una
extensión plana y semiplana entre unos 250.000 y 280.000 Km2 que comprenden los
estados Cojedes y Guárico (llanos centrales), Barinas, Apure, Portuguesa (llanos
orientales), y Anzoátegui y Monagas (llanos orientales).Es un área realmente
grande que predomina la vegetación herbácea y de sabana, parches de bosques
llamadas “matas”, bosques de galerías o ribereños, zonas inundadas, morichales y
otros tipos de vegetación, pero sin duda lo más predominante es la gran
diversidad de fauna que sustenta, y la gran facilidad de poder disfrutar de un
buen espectáculo de fauna silvestre. Desde hace muchos años existen hatos
privados y otros que se encuentran bajo el control del gobierno lo cuáles de han
dedicado por muchos años a la conservación de su fauna y hoy en día son
verdaderos santuarios de vida silvestre. Sin embargo, en otra entrega de esta
Guía Turística les recomendaré los mejores hatos de Venezuela para observar
fauna silvestre y que conjuguen el buen servicio y la calidad humana de sus
anfitriones.Para mí una de las grandes maravillas que reguardan nuestros llanos
son los fantásticos delfines de ríos o comúnmente llamadas “Toninas”, o cómo se
le conoce científicamente como Inia geoffrensis, que es una de las seis especies
de delfines de agua dulce que existen en el mundo. En contraste con otras
actividades humanas que la amenazan, la tonina, o delfín del Orinoco, es
protagonista de numerosas leyendas que la ensalzan y protegen a nivel local.
Conocer sus secretos es amar a esta especie, por ello aquí te detallamos sus
apasionantes conductas y características únicas para invitarte a disfrutarlos en
su hábitat natural. Mi amigo el médico veterinario de fauna silvestre Ernesto
Boede me comenta que el nombre común de “tonina” viene de la palabra “toñina”
que era como los navegantes españoles denominaban a los grandes atunes y a los
delfines marinos, creyendo erróneamente que estos entraban del océano Atlántico
al río Orinoco y de allí a la totalidad de nuestros llanos. Poder ir a ver a las
toninas en su propio hábitat es una experiencia inolvidable que toca el corazón
de cualquier persona, se muestran elegantes, curiosas, simpáticas y sin dudas
muy mágicas, su distribución abarca la cuenca del Orinoco, desde el Alto Orinoco
al sureste del estado Amazonas hasta el Delta Amacuro y por todos de sus más de
200 caños, y más fácilmente es posible verlas en los ríos llaneros de los
estados Cojedes, Guárico, Apure y Barinas, así como también en los ríos Sipapo,
Cuao, Autana, Ventuari, Caura son relativamente fáciles de observarlas, pero sin
duda uno de los mejores lugares en donde podrán disfrutarlas es en el río
Portuguesa  hacia los lados de los Esteros de Camagüán. Los machos de las
toninas son cetáceos solitarios, sólo se pueden ver en pareja cuando están en
época reproductiva, pero si es posible ver grupos maternos de hasta 6 hembras
junto a sus crías y juveniles en casi cualquier época del año. Una madre sólo
pare una sola cría y esta puede permanecer junto a ella hasta los siete años que
es cuando alcanza su madurez sexual y se separa de su madre para enrumbar su
propio camino por las aguas de nuestros ríos llaneros, amazónicos y guayaneses.
Las toninas son animales longevos que pueden llegar a vivir entre los 35 a 40
años de edad.A simple vista las toninas pueden parecer animales muy tiernos y
dóciles, pero en realidad son animales que están en el tope de la cadena
alimenticia, son depredadores muy aguerridos que pueden llegar a medir hasta
2,50 metros , y pesar hasta 180 Kg., y cuando se trata de defender a sus crías
son animales feroces que con sus fuertes aletas caudales, sus alargados y
cilíndricos hocicos, sus más de 100 afilados dientes y su sistema de
“ecolocalización” atacarán sin dudarlo dos veces a cualquier intruso sea animal
o humano que sientan como amenaza, pero mientras se respete su espacio, no se le
estresen y sólo se les admire tranquilamente desde un bote es un espectáculo
digno de disfrutar y valorar los tesoros que nos brinda nuestra generosa
naturaleza.En países como Brasil, Perú y Colombia han sabido muy bien cómo
atraer a turistas especializados para la observación de toninas o delfines
rosados, la observación de cetáceos marinos sabemos que es una de las tendencias
“ecoturísticas” que más ingresos generan en el mundo, ahora nos toca aprovechar
y saber explotar muy responsable y éticamente un producto tan maravilloso pero
frágil como podría ser la observación de toninas o delfines de río. Para mí es
un producto increíble que envuelve muchísimos aspectos increíbles, cómo todas
las maravillosas leyendas que encierra a esta increíble especie, también la
cultura del llanero o del indígena, y aunado a los espectaculares paisajes de
nuestras selvas y sabanas venezolanas lo hacen un producto ecoturístico muy
atractivo a los especialistas de los cetáceos de agua dulce y a todos aquellos
ecoturistas especialistas en fauna silvestre en general.Me cuenta el
especialista Ernesto Boede que una de las tantas leyendas sobre las toninas es
que es un animal respetado sobre todo por el llanero venezolano. Los pescadores
más viejos opinan que las toninas son enamoradizas y hay que tenerles respeto,
salen de noche en los pueblos transformándose en esbeltos galanes a enamorar a
las bellas mujeres y si se descuidan se las llevan al río, las ahogan y se
transforman en preciosas toninas. Pero si hay algo cierto es que se sabe que
muchas veces, cuando alguna persona se está ahogando en un río, las toninas la
ayudan y la salvan empujándola hacia la orilla.Cuando el naturalista y
explorador Alexander von Humboldt hizo sus viajes viaje por el río Apure,
Orinoco y Brazo Casiquiare en 1800 y vio por primera vez a las toninas o
delfines del orinoco relató lo siguiente: Pero para el Delfín Rosado no todo es
color de rosa, sufre serias amenazas y el Libro Rojo de la Fauna Venezolana la
cataloga como especie “vulnerable” de extinción, debido a la deforestación de
las selvas del sur de Venezuela, la alteración de su hábitat por la construcción
de represas, diques y compuertas, el tráfico fluvial, la contaminación de las
cuencas por la minería –mercurio y metales pesados- y el desagüe de aguas
cloacales, la fragmentación del ambiente para la agricultura y ganadería
extensiva. De igual forma la sobrepesca atenta con las presas de las que se
alimentan las toninas y las grandes redes de pesca artesanales representan un
gran peligro para esta especie ya que en ellas mueren enredadas, y también en
algunas localidades usan a la tonina como carnada para la pesca de una especie
de bagre muy buscada.Los invito a deleitarse con esta bella experiencia de poder
ver a esta fantástica especie en su hábitat natural y les aseguro que se
sentirán cómo si estuvieran en los relatos del explorador y científico Alexander
von Humboldt o en alguna leyenda o novela de nuestros llanos venezolanos. Les
recomiendo contactar a mi gran amiga Sorelia Franco (soreliafranco@gmail.com) o
a mi amigo Ricardo Freitas (agropecuariahatolascaretas@hotmail.com), ellos mejor
que nadie podrán llevarlos a observar a estos enigmáticos y hermosos delfines de
ríos, que son de las especies más representativas de nuestra fauna venezolana y
que debemos comprometernos por su conservación. Así que amigos les recuerdo que
debemos vivir con responsabilidad ambiental y que el futuro de nuestras
generaciones comienza por nosotros.blancoalb@gmail.com

** Bitcoin: ¿Riesgoso o muy bueno?

[[http://www.eluniversal.com/noticias/economia/bitcoin-riesgoso-muy-bueno_681286][Bitcoin:
¿Riesgoso o muy bueno?]]

Tras subir más de un 1.500% en lo que va de año y enfilarse por encima de los
$17.000 a solo dos semanas de terminar el 2017, el Bitcoin ha dejado atrás de si
un avance meteórico además de posiciones divididas sobre su futuro y alcance. ,
pues es precisamente esta volatilidad la que genera grandes ganancias, pero
también grandes pérdidas. Este año, el Bitcoin ha ganado más de 17 veces su
valor desde los $997 con los que arrancó el mes de enero, siendo que a partir de
la segunda mitad del 2017 los precios se desencadenaron en lo que vemos ahora.En
un año donde la criptomoneda ha visto grandes avances y algunos retrocesos seria
común preguntarse: ¿qué ha sido lo más resaltante que ha pasado? Enumerando
algunos sucesos encontramos: la ampliación de la brecha con el oro, la
legalización de la moneda como forma de pago en Japón, el nacimiento del Bitcoin
Cash, los múltiples ataques de hackers a las plataformas de intercambio y
minado, los fuertes controles que ha implementado China en contra del Bitcoin y
el inicio de los contratos a futuros de este por parte de Cboe Mercantil
Exchange y pronto por CME Group (Chicago Mercantil Exchange)., pues la entrada
de estos instrumentos no solo ha atraído a nuevos players al mundo de las
criptomonedas, sino que  han logrado que inversores más convencionales como JP
Morgan o incluso Goldman Sachs evalúen la opción de negociar con estos futuros
frente a las peticiones de sus clientes.El pasado domingo 10, estos instrumentos
entraron al mercado bajo el símbolo XBT contando con un precio que oscilaba
entorno a los $17.700. Asimismo, el estreno de los XBT tuvo un inicio lento pero
alcista puesto que en sus primeras horas de negociación se habían adquirido 800
contratos con vencimiento en enero. En esta misma línea, la prima de los futuros
fue mayor de lo esperada llegando incluso a cotizarse en $1.300 por encima del
Bitcoin (BTC). A pesar del gab inicial, la diferencia se ha comenzado a cerrar
conforme el BTC se ha acercado a  los $18.000.El número de fondos de cobertura
que han comenzado a invertir en criptomonedas se ha triplicado en tan solo
cuatro meses, al pasar de 55 para finales de agosto a 170 en diciembre, según
datos de Autonomous Next. Este repunte del interés institucional le ha concedido
una mayor legitimidad a las monedas digitales, aunque este logro no
necesariamente se traduce en una disminución de los riesgos inherentes a
estas. El sorprendente desempeño que ha presentado el Bitcoin no es algo para
tomar a la ligera, pues la capitalización de este ya supera los $275.000
millones. Una cifra considerable si tomamos en cuenta que la capitalización de
la criptomoneda supera a grandes empresas de vieja data en los mercados como:
Visa Inc ($257.120 millones), Intel Corporation ($202.780 millones), Coca-Cola
($192.270 millones) y Walt Disney Company ($162.250 millones).La capitalización
de mercado del BTC ha dado un salto gigantesco en poco más de 5 meses, ya que si
tomamos en cuenta que para junio esta se encontraba entorno a los $41.900
millones, estaríamos hablando de un salto de 556% hasta los momentos. Pero el
dominio que ha mostrado la moneda no queda aquí, pues el Bitcoin representa un
poco más del 52% del total de capitalización de mercado de las criptomonedas,
seguido por el Ethereum (ETH) con 12,91%, el Bitcoin Cash (BCH) 6,09% y Ripple
(XRP) con un 5,32%. El restante 20,89% se encuentra conformado por las más de
1300 monedas digitales que se pueden transar.A pesar de la popularidad del
Bitcoin, hay otras monedas digitales que han reportado desempeños mejores que el
BTC, llegando incluso a superar el 7.000% en lo que va de 2017. Estas subidas
más que meteóricas han sido reportadas por el Ethereum (ETH), el cual ha ganado
un 8.064% en los últimos once meses y medio al pasar de $8,17 hasta $667. Por
atrás del ETH, se encuentran el Dashcoin (DASH) y el Litecoin (LTC) que han
exhibido aumentos de 7.611% y 5.865% respectivamente. Asimismo, el boom de las
criptomonedas ha sido tal que el Bitcoin Cash, el cual no tiene más de 6 meses
de vida, ha ganado un 330% al ascender desde los $413 que marco en su primer día
de transacciones hasta $1.775.Dejando a un lado la moneda más popular, tenemos
que Ethereum cuenta con una capitalización de casi $66.000 millones, seguido del
Bitcoin Cash ($26.901 millones), Ripple ($17.000 millones) y Litecoin ($16.372
millones).

** Centro Nacional de Teatro está preparado para un exitoso 2018

[[http://www.eluniversal.com/noticias/entretenimiento/centro-nacional-teatro-esta-preparado-para-exitoso-2018_682042][Centro
Nacional de Teatro está preparado para un exitoso 2018]]

Aún no ha terminado el año 2017 y ya los creadores del teatro vislumbran un buen
2018 para el género. El Centro Nacional de Teatro ya tiene los nombres de los 44
artistas que conformarán su elenco durante todo el próximo año, y que desde ya
preparan los guiones de 18 obras —entre estrenos, coproducciones y reposiciones—
que conformarán el catálogo oficial de la institución estatal.Las dos maestras
del teatro venezolano, Aura Rivas y Francis Rueda, ambas ganadoras del Premio
Nacional de Cultura, dominan el elenco en el que también destacan las actrices
María Alejandra Tellis y Marcela Lunar, todas ellas parte del staff de actores
que este año subieron al escenario del Teatro Nacional para presentar El pez que
fuma, uno de las obras más vistas por los caraqueños este año y que podrá volver
a disfrutarse en 2018.El director Carlos Arroyo fue parte del jurado que
seleccionó a los referidos 44 talentos. "Pienso que como jurado hicimos un
trabajo importante y muy minucioso. Gracias al elenco que tenemos sabemos que
los espectáculos serán de una calidad y capacidad atractiva importante", declaró
el creador durante un encuentro con los medios de comunicación.Piezas
fundamentales de las tablas venezolanas como Baño de Damas, escrita y presentada
en 1986 por el maestro Rodolfo Santana —uno de los autores nacionales más
interpretados en América Latina—, y otras como la ópera Do Malandro, original
del brasileño Chico Buarque, forman parte de los seis estrenos que presentará el
centro durante el año 2018, bajo la dirección, además, de directores notables
como Miguel Issa, según reseñó AVN."Gracias a este elenco sabemos que los
espectáculos serán de una capacidad atractiva importante. Queremos que cada obra
sea de alto impacto y que logre atraer una mayor cantidad de espectadores a las
salas", añadió Arroyo.Además de El pez que fuma, otra de las grandes
producciones que en este 2017 presentó el Centro Nacional de Teatro fue Troyanas
nuestras, una pieza que supo combinar el teatro griego con los ritmos populares
venezolanos, todo esto bajo la visión de otro maestro de las tablas en
Venezuela: Costa Palamides.

** El "Retablo de las maravillas" llega por primera vez a Ucrania

[[http://www.eluniversal.com/noticias/cultura/retablo-las-maravillas-llega-por-primera-vez-ucrania_681975][El
"Retablo de las maravillas" llega por primera vez a Ucrania]]

.- El teatro satírico de Cervantes llegó por primera vez a Ucrania con el
estreno del , una adaptación contemporánea de un clásico del Siglo de Oro que
resalta los defectos y virtudes de la naturaleza humana."Es una obra basada en
un cuento medieval de gran calidad literaria y muy divertida. Se escribió hace
más de 400 años, pero es actual porque habla de lo que siempre es cierto, de la
naturaleza humana", dijo durante la presentación el primer consejero de la
Embajada de España en Kiev, Jorge Soler.Con una extravagante y divertida puesta
en escena, el Teatro Suzirya de Kiev estrenó ayer este entremés de Miguel de
Cervantes en ucraniano. muestra la dimensión más humanista del pensamiento
cervantino a través de una exhibición sarcástica de los complejos individuales
creados por la ignorancia y la mentira.Dirigido por Irina Batkó-Stupka y con
libreto basado en el libro traducido al ucraniano por Julia Mijailuk, el
espectáculo utiliza un juego de ilusiones teatrales combinado con un marcado
lenguaje popular para mostrar a unos cómicos personajes que son rehenes de las
medias verdades y de las distorsiones de la realidad.Saber contar la verdad de
uno mismo y tener la capacidad de escuchar y entender la cruda realidad dicha
por los demás constituye el tema central de esta historia, que fue escrita al
final de la vida de Cervantes.Como explica Soler, pese a haber sido escrita hace
siglos, esta accesible pieza se expresa como metáfora de nuestros días al
mostrar actitudes comunes, ya que las personas siguen formando sus propias
impresiones sobre ideas "ajenas".La versión ucraniana de la obra muestra la
disparatada trama en un claro paralelismo con la sociedad actual, pero sin
perder la fidelidad a los rasgos esenciales del ácido discurso cervantino, que
hace una feroz crítica a la decadencia ética de la España de la época.Chanfalla
y Chirinos, personajes del mundo carnavalesco que habitan en un Retablo mágico,
son llevados de forma original a la escena para resaltar la hipocresía, los
anhelos y bajezas de los habitantes de un pueblo, y se yuxtaponen con el símbolo
de poder y mediocridad representado por sus gobernantes.En esta escenificación
de la obra, que permanecerá en el repertorio del Teatro Municipal de Kiev, el
núcleo central de la música lo constituye una guitarra flamenca acompañada de un
violín, y el toque español lo aportan también bailarinas y cantantes.Se trata de
un "hito histórico", al ser la primera vez que se lleva al teatro una obra de
Cervantes en este país eslavo, como señaló a Efe el presidente de la Asociación
de Hispanistas de Ucrania, Oleksandr Pronkevich, durante el estreno."Es un paso
muy importante, que el público ucraniano conozca y experimente con la palabra
universal de Cervantes", aseguró, al tiempo que destacó el "gran conocimiento e
interés" que existe en Ucrania por la cultura y la lengua española.El Retablo de
las maravillas es una de las tres únicas obras de Cervantes que se han traducido
al ucraniano en un país en el que, a juicio de Pronkevich, la tradición
hispanista es bastante reciente pero va más allá del idioma.El estreno de la
obra cerró un provechoso año de actividad cultural por parte de la Embajada
española en Kiev, junto con la reciente donación de 800 libros de autores
clásicos en español a la Biblioteca Nacional Infantil de Ucrania, especialmente
diseñados para estudiantes de la lengua española.

** ¿Cómo que no puede celebrar esta Navidad? Vea cómo sí

[[http://www.eluniversal.com/noticias/estilo-vida/como-que-puede-celebrar-esta-navidad-vea-como_680976][¿Cómo
que no puede celebrar esta Navidad? Vea cómo sí]]

La Navidad es una de las épocas del año que más expectativas trae para la
mayoría de las personas. Por razones religiosas o comerciales, son días en los
que las disposiciones se concentran en disfrutar, en ser abundantes, más aún con
los seres queridos, siendo la familia el centro de todos los buenos deseos.¿Pero
qué hacer cuando no es posible, cuando lo material y hasta quienes amamos no
están?psicopedagogo y orientador familiar. “Hay que reconocer que no estamos en
las mismas condiciones que en los otros años, hay un momento distinto,
diferente, en el que no vamos a poder tener lo que en otros años tuvimos, o
disfrutar lo que en otros años disfrutamos”.Pese a eso, lo que sí resalta es que
hay celebrar esta época de fin de año, y no solo por razones religiosas sino
ampliamente existenciales. “Estamos llamados a abrir nuestro corazón y nuestras
manos, porque somos pasajeros por este mundo, estamos de tránsito, y lo bueno de
la vida es pasar por ella haciendo todo el bien y dejando amigos”, menciona el
padre John González, párroco de la parroquia San Miguel Febres Cordero, en
Mérida y capellán de la policía estadal.Para él, eso es posible lograrlo en
medio de las vicisitudes, confirmándolo en la reunión familiar, cuando cada uno
dice qué puede aportar para bendecir este diciembre. “No hay mal que dure cien
años ni cuerpo que lo resista, esta es la esperanza de un pueblo que resiste y
lucha contra toda desesperanza”, asegura.Y es que Eso se traduce también en ser
solidarios, en ver de qué manera vamos a compartir con otros que realmente no
tienen nada. “En nuestra comunidad ya nos estamos preparando para los abuelitos,
para los niños que no tienen, para poder hacerles una comida y compartir con
ellos” esta Navidad.A partir de los símbolos que en la Navidad están presentes
en casi todas partes, Misle, fundador y director de del Centro Comunitario de
Aprendizaje (Cecodap) sugiere repasar qué significan en la vida personal y qué
hacer con ellos este año.“Eso que uno hace mecánicamente, adornar el arbolito,
poner un pesebre y colocar una estrella, todo tiene un sentido que la gente
desconoce. Veamos cómo con esos símbolos hallamos nuevos significados en este
momento”, plantea. Observemos bien, el pesebre en esencia es un grupo familiar,
la escena del nacimiento con mucho amor de un niño,  en condiciones muy
humildes. No hay que dejar por fuera toda la importancia que tuvo la comunidad
en ese hecho, que fue a visitar, a honrar, a reconocer a ese niño que
representaba la esperanza.  Sea en el pesebre o en el arbolito, hay que recordar
que ella fue la que guió a los pastores y a unos tres reyes magos a visitar al
Niño Jesús. “En la familia podemos conversar sobre ¿cuál es esa estrella que nos
guía?. ¿Quiénes son esas personas que nos orientan, que nos inspiran?. ¿Será una
tía, el abuelo, o un amigo muy cercano a la casa? Es ver cómo cada uno también
tiene una estrella que lo guía, lo orienta y lo acompaña”. En los momentos de
oscuridad o penumbra la luz siempre es muy ansiada. En la Navidad las luces
están presentes en la decoración del arbolito, en el pesebre y en la casa en
general.  “Esas luces las podemos colocar también con velitas en la casa. ¿Qué
significa para nosotros que estemos juntos, vivos, con salud, que hayamos podido
superar juntos situaciones difíciles?”. Encontrar la respuesta a eso puede ser
la propia luz interna que guíe los días del año que está por venir. En vez de
peticiones de regalos puede ser de deseos, o también una de agradecimientos.
“Puede ser una carta para pedir por la familia, o para agradecer por lo que
significa en esta dificultad lo que hemos logrado mantener, quizás estar juntos;
cada quien va a identificar lo que tiene que agradecer”. Hay que redescubrir que
estos días siguen siendo una buena oportunidad para el intercambio con los seres
queridos, no de regalos sino más bien tornarlos en visitas.“Haciendo énfasis en
que no vamos a comer en casa de los primos, de los abuelos, como antes, sino que
vamos a compartir, es decir, vamos a llevar algo que permita pasar el momento
juntos, y, si se puede, algún detallito que no tiene que ser un regalo”.Sin
pretender justificar las razones que pueden trastocar lo que durante muchos años
fueron las costumbres personales y tradiciones al celebrar la Navidad, quizás se
descubra que Quien sabe de cómo hacer magia una noche de Navidad es Armando
Quintero, escritor, ilustrador y cuentacuentos que hace años lo logró con los
niños y adultos de la comunidad donde vive.Resulta que por aquel entonces los
amiguitos de sus hijas pequeñas le dijeron que querían tener una “Navidad
diferente”. Y, luego de que todos ahorraron para tener el dinero, compraron
cartulinas de colores y marcadores, además de que buscaron papel periódico y
bolsas de plástico para ponerse a inventar.“Hicimos paracaidistas y avioncitos
de papel. Cada paracaidista tenía un mensaje en sus manos, inventados. Igual los
avioncitos”, recuerda este fundador de Los Cuentos de La Vaca Azul.Una noche,
cuando tenían muchos, los lanzaron desde la azotea del edificio hacia las áreas
comunes de la comunidad. “Al enterarse de lo que habíamos hecho al rato nos
llamó la asociación de vecinos diciéndonos que querían una reunión.
Aparentemente era un regaño, pero como se enteraron de que queríamos una Navidad
distinta, el presidente de la junta de vecinos nos dijo ‘Aquí la tienen’. Y
aparecieron los padres con comida que recolectaron y se hizo una fiesta en
común”.Y con su tono dulce de abuelito, nos dice sin dudar: Para adornar un
árbol de Navidad bien bonito basta con buscar una rama seca, y se pueden hacer
adornos con los tubitos del papel higiénico, con recortes de revistas o con
papel de aluminio.Generalmente en esta época del año se hace un inventario y
extrañamos los que ya no están, porque se fueron o porque murieron. Por eso En
el caso de Venezuela este año tiene una connotación particular porque la
migración ha sido mayor, ocasionando la separación de los integrantes de muchas
familias.“Habrá quien diga yo no quiero celebrar la Navidad, yo me  quiero
acostar a dormir, eso hay que respetarlo”, comenta Misle, quien también es
psicopedagogo.Dice que no se debe reprimir, esconder, ocultar la sensibilidad,
sino más bien dejar salir las lágrimas si se presentan. Sugiere que más bien se
puede recordar con amor esos seres que ya no están, rememorar las situaciones
agradables, si hubo un acontecimiento que los unió, y, aprovechando las
oportunidades que brindan los recursos tecnológicos, buscar las formas para
contactar a esos seres que están lejos de uno.Así, encontrando oportunidades en
medio de las limitaciones, ganancias en las pérdidas, en este momento cada quien
tiene en sus manos decidir qué paso quiere dar. No hay duda de que se trata de
lo trascendente: lo afectivo, lo espiritual, para poder tener unas Navidades más
sentidas. Saluda a los amigos,escucha este cantar,abraza a todo el mundo,desea a
todos paz.Deja las penas,ponte a soñar,¡la Tierra enterade fiesta está!Hoy ha
nacidoen un portalun dulce niño,¡Es Navidad!(Orquídea Marinozzi)

** Secuestradores madrugan en la Fajardo

[[http://www.eluniversal.com/noticias/sucesos/secuestradores-madrugan-fajardo_681328][Secuestradores
madrugan en la Fajardo]]

La zona este de la autopista Francisco Fajardo se ha convertido en una de las
principales áreas de operaciones de las bandas de secuestradores establecidas en
Caracas. Las víctimas denuncian que son grupos integrados por al menos 12
delincuentes, que se trasladan en camionetas de lujo, armados con fusiles de
asalto y chalecos antibalas.El apresto operacional de estas mafias les permite
cometer sus secuestros a plena luz del día, y de forma simultánea pueden tomar
de seis a nueve personas como rehenes, esto según el abogado criminalista y
experto en temas de seguridad, Fermín Mármol García.Fuentes policías ligadas a
la investigación de estos hechos indicaron que solo en noviembre se presentaron
15 casos de secuestros en las inmediaciones de los distribuidores Altamira,
Caurimare, Macaracuay y Metropolitano de la vía expresa más grande de
Caracas.Pese a que el director de la Policía Nacional Bolivariana, Alfredo Pérez
Ampueda,  anunció una disminución considerable de este delito en varias zonas de
Caracas, Mármol considera que esta estimación se debe a que los organismos
policiales solo se enfocan en los secuestros que son denunciados por la
ciudadanía.A juicio del experto, en el país solo se denuncia un aproximado del
30% de los secuestros perpetrados, esto debido a que existe una gran
desconfianza en la población por los cuerpos policiales designados para combatir
dicho flagelo.Además, aseguró que aunque durante el segundo trimestre del año se
presentó un descenso en los casos registrados, fue porque durante las protestas
ciudadanas se efectuaron cierres en las principales calles del este de la ciudad
y esto dificultó que las mafias pudieran circular por esas zonas.De acuerdo a lo
manifestado por las fuentes policiales, la manera en la que se ejecutan los
secuestros en Caracas ha evolucionado en comparación a los modus practicados a
principios de año.En los últimos meses se han registrado mayor número de
secuestros exprés, es decir en un tiempo menor a las 24 horas de
cautiverio.Aunque las grandes bandas responsables de estos delitos siguen
ubicadas en los barrios de la Cota 905, El Cementerio y El Valle, las víctimas
no son llevadas hasta estas zonas populares, sino que son “ruleteadas” por la
ciudad mientras se acuerda el pago por su liberación tal como lo precisa la
fuente policial. Mármol García, confirma esta práctica y además agrega que en
algunos de los casos los rehenes son puestos en cautiverios en galpones o
talleres mecánicos,  donde los obligan a realizar transacciones a favor de los
plagiarios.Esto le dificulta aún más a los cuerpos de seguridad poder frustrar
los secuestros, y las estadísticas presentadas por el Observatorio de Delito
Organizado dan fe de ello.Entre los meses de julio y septiembre de este año,
solo se han podido frustrar 29,6% de los secuestros cometidos, lo que representa
un descenso del 13% en relación al mismo trimestre del año pasado.En cuanto al
cobro de los rescates, fuentes policiales indicaron que en alguno de los casos,
los antisociales piden como pago que los familiares de las víctimas entreguen
vehículos hasta en  la frontera con Colombia para ser comercializados en el
vecino país.Entre los grupos  de secuestradores que operan en Caracas y que son
investigados por el Cicpc, se encuentra las bandas de “El Coqui”, “El Galvis”,
“El Juvenal”, “El Bemba” y “El Quilombo”.Sin embargo, este delito se ha
masificado y según Mármol, actualmente existen pequeñas organizaciones que se
han fortalecido debido al cobro de rescates en moneda extranjera.Es por ello que
se evidencia tanto músculo bélico en manos de estas mafias.El director la ONG
Observatorio Venezolano de Prisiones, Humberto Prado, denunció que los
principales ejes de secuestros del país son controlados directamente desde las
cárceles, y los organismos policiales no están facultados para desarticular
estas redes delictivas dentro de las prisiones, pues son competencias directas
del Ministerio Penitenciario.

** Los primeros días en casa

[[http://www.eluniversal.com/noticias/suplementos/los-primeros-dias-casa_681626][Los
primeros días en casa]]

A diferencia de otros regalos que se entregan en estas fiestas, los perritos no
vienen con un manual de instrucciones. Por ello, te contamos qué debes
considerar para comenzar a cuidar a tu nuevo amigo.Lo primero que debes hacer es
dejarlo recorrer cada espacio para que huela todo lo que tenga que oler. Luego
de su exhaustivo análisis olfativo, podemos mostrarle sus espacios. Le
marcaremos las zonas de juego y el designado para hacer sus necesidades. Hay
personas que les colocan papeles de periódico. El perro sentirá su olor y sabrá
que tiene que hacer ahí.Los primero días, déjale a disposición algunos juguetes.
Estar rodeado de peluches seguramente le entretendrá en el caso de que se
despierte en mitad de la noche. También es muy importante tener un espacio para
comer y beber. Infórmate sobre su alimentación y horarios y, poco a poco, lo vas
adaptando.Los cachorros son curiosos, evita los accidentes y coloca fuera del
alcance los productos de limpieza, los cables eléctricos, las plantas tóxicas y
otros objetos que pueden llamar su atención, pero es mejor que no toque.Otro
aspecto a considerar es su salud, pregúntale a quien te lo regaló qué edad
tiene, si tiene un control de vacunas. Si no tiene la información de su salud,
llévalo a un veterinario. Así sabrás las vacunas que le hacen falta y te dará
algunos consejos sobre su cuidado, educación y socialización. En caso de ser un
adulto, al comienzo y sobre todo la primera noche, será un tanto inseguro y
echará de menos su antiguo hogar. Por ello, para aumentar su grado de seguridad,
habitúale desde el principio a su nuevo rincón. Para crear este espacio y
prepararte a pasar una noche tranquila, puedes seguir muchos de los consejos que
valen también para cachorros y recuerda que una cama cómoda, tranquilidad y
paciencia por tu parte es lo que más necesitará.Recuerda también que un perro
adulto, puede venir con normas ya establecidas de su anterior hogar. No olvides
que tienes siempre profesionales que podrán ayudarte si en algún momento no
consigues adaptarlo al nuevo ambiente luego de varias semanas. Enséñale las
buenas costumbres desde el principio y no esperes a que desarrolle malos hábitos
para luego corregirlos. Sé coherente y paciente, es la manera mejor de empezar
con buen pie la relación. Si no quieres que se suba a los muebles o a la cama,
acostúmbralo desde el principio a dormir en su espacio y a respetar la zona
prohibida. Enséñale a esperar antes de comer o de salir a pasear.Utiliza premios
para enseñarle y la educación se convertirá en un momento divertido que
estrechará un lazo afectivo.El aprendizaje ha de ser continuado. En los primeros
días en su nueva casa debes hacer un esfuerzo para buscar unos minutos al día y
educarle. Recuerda que tú mandas y él o ella debe obedecer.La familia completa
debe mantener una misma línea de educación hacia el nuevo perro que llega a
casa. Si desde el comienzo, por ser Navidad, le das permiso para subirse a los
muebles o a las camas, el cachorro o perro ya mayor entenderá que así debe ser
siempre. Así que establece con tu familia qué reglas le van a poner, todas
acordadas.El nuevo perrito, aún siendo mayor, no habla tu idioma, solo entiende
de gestos correctivos, por ello, en el proceso de educación trata de lucir
firme, pero no molesto con su presencia. Aunque no entiendan tus palabras, los
gestos y tu energía sí las percibe de manera clara. Por ello, aplica la
paciencia y el premio afectivo (palmadas y abrazos).El perro que recién se
incorpora a la vida familiar debe estar en tu dinámica diaria. Si lo acostumbras
a salir a la calle para hacer sus necesidades, tienes que hacer el hábito.
Recuerda también que al igual que tú y tus seres queridos, un perro requiere
entretenimiento y diversión. Si son varios en tu casa, pueden alternarse los
paseos entre todos.El perro que llega a casa debe tener agua y comida
establecidas para que no se sienta hambriento y desasistido. Ten un espacio
claramente definido para él y coloca allí el agua. Sobre la comida, expertos
recomiendan establecer horarios puntuales para que se haga el hábito. La comida
para perros servida en porciones pequeñas garantiza su frescura.

** Meryl Streep en la mira por su amistad con Weinstein

[[http://www.eluniversal.com/noticias/cine/meryl-streep-mira-por-amistad-con-weinstein_681955][Meryl
Streep en la mira por su amistad con Weinstein]]

.- Meryl Streep arrancó aplausos a inicios de años por su discurso de rechazo a
Donald Trump; 12 meses después, su nombre está en la mira por el escándalo
sexual que sacude Hollywood.La actriz de 68 años, ganadora de tres Óscar, está
bajo ataque por su insistente rechazo a cualquier conocimiento de la conducta
del magnate del cine Harvey Weinstein, acusado de pasar su carrera acosando,
abusando, intimidando y violando mujeres.Streep trabajó en varias producciones
de Weinstein y se refirió a él como “dios”, en broma, durante los Globos de Oro
de 2012.De las más grandes actrices de su generación, ha tenido una brillante
carrera de 40 años en la que ha interpretado desde una sobreviviente de un campo
de concentración nazi hasta una madre cantante de ABBA.Consiguió su primera de
un récord de 20 nominaciones al Óscar en 1979 con su papel en el drama de
guerra  y ha ganado la estatuilla en tres oportunidades, la última en 2012 por
su papel como la primera ministra Margaret Thatcher en , distribuida por la
empresa de Weinstein.Fue su activismo político el que se llevó los titulares
cuando en su discurso al recibir un premio honorífico en los Globos de Oro
denunció a Trump, ganando alabanzas y algunas críticas.Cuando la olla Weinstein
fue destapada a principios de octubre dijo que estaba “horrorizada” por las
“deshonrosas” denuncias de la que aseguró entonces no tenía idea.Pero no todos
compran esa versión, particularmente los activistas del movimiento en redes
sociales ¡MeToo! –¡YoTambién!, en español– contra el abuso sexual, que han
llegado a la conclusión de que aquellos más cercanos al productor sabían de su
comportamiento y decidieron ignorarlo.Rose McGowan, que alega haber sido víctima
de Weinstein y es una de las principales activistas en su contra, la criticó por
su intención de vestir negro en una “protesta silenciosa” en los Globos de
Oro."Tu silencio es el problema", escribió en Twitter, y luego lo borró.
"Desprecio tu hipocresía".Streep respondió el lunes en un comunicado enviado
al  en el que insistió que desconocía la conducta del influyente productor,
investigado por la policía de Nueva York y Los Ángeles. "No guardé silencio
deliberadamente, no sabía, no apruebo la violación", dijo.Este texto no logró
apaciguar las críticas en su contra. Por el contrario, el martes decenas de
afiches aparecieron en Los Ángeles, acusando a Streep de facilitar las acciones
de Weinstein, que ha dicho que todas las relaciones sexuales fueron
consensuadas. Sabo, un artista callejero de 49 años y exintegrante del cuerpo de
Marines de Estados Unidos, asumió la autoría de estos afiches en los que una muy
sonriente Streep aparece al lado del productor y sobre sus ojos una franja roja
con el texto “Ella sabía”.Explicó que la campaña es una represalia a la actriz
por usar su más reciente filme  para atacar a Trump, quien también fue acusado
de abuso sexual por 16 mujeres.El columnista de entretenimiento Ira Madison III
escribió que siente que Streep dice la verdad y que estos ataques por el caso
Weinstein no son más que una manifestación de sexismo en el mundo de
espectáculo."Aquí estamos atacando a una mujer por algo que tal vez sabía o no,
cuando todo el mundo insiste en que todos en la industria sabían", zanjó. "¿Por
qué entonces George Clooney o Brad Pitt no han sido atacados tan agresivamente
como a Streep? ¿Por qué no Bob Weinstein, su propio hermano, quien ha salido
relativamente ileso de la caída de Harvey?".Pero el público no parece darle el
beneficio de la duda.Jeetendr Sehdev, experto en imagen de celebridades, recoge
dos veces al año la opinión de 2.000 personas al azar en Estados Unidos sobre
los ricos y famosos como parte de un estudio que inició en 2012.Dijo que 58% de
los consultados en octubre sobre el caso Weinstein manifestaron rechazo hacia la
actriz."Las afirmaciones de Streep de que ella no sabía [sobre Weinstein] son
ridículas y un beso de la muerte para su imagen en Hollywood", dijo a AFP el
exitoso autor de . Acusó a la aclamada actriz de subestimar la inteligencia del
público y el coraje que mostraron sus colegas que lo denunciaron, al tiempo que
dijo que Clooney también tiene explicaciones que dar."Mucha gente asume que
Weinstein buscaba a sus amigos más cercanos para ver si podían hablar a su favor
para tratar de reducir los daños. ¿Eran Streep y Clooney parte de ese pacto?".

** La alimentación incide en el estado de ánimo

[[http://www.eluniversal.com/noticias/suplementos/alimentacion-incide-estado-animo_680111][La
alimentación incide en el estado de ánimo]]

La sabiduría ancestral de los diferentes pueblos del mundo enseña los beneficios
de sus alimentos autóctonos para el cuerpo y la mente. Hace décadas que la
ciencia estudia esta relación y que las corrientes de crecimiento espiritual
promueven una alimentación sana.Explica la sanadora integral (terapia
bionergética, gestalt y musicoterapia), Iraida Natera que al referirnos a los
estados de ánimo estamos hablando de los 7 modos de la energía vital, los cuales
se manifiestan en una frecuencia de vibración en colores, definidos dentro de
las teorías de la física cuántica. “Y todos en un mismo nivel de
importancia”.Cada alimento natural tiene un efecto “dinamizante” en un espacio o
sector del cuerpo. Es también posible que el exceso o carencia de una
“frecuencia” nos influya orgánicamente y,  por ende, puede influir en la actitud
emocional.Hasta ahora la ciencia nos habla de seis tipos de energía y una
séptima, que es combinación de dos, que se manifiestan para permitir el
funcionamiento de nuestro organismo.Y tenemos siete grupos de alimentos básicos
que deben ser consumidos para mantener un equilibrio nutricional, idealmente una
porción de cada grupo al día, evitando excedernos en ningún grupo nos mantendrá
sanos. El elemento fundamental contemporáneo de la buena alimentación es la
información y educación. Por ejemplo, Algunos ejemplos de los grupos de
alimentos son proteína de origen animal, huevo, carne, leche; vegetales verdes,
lechuga, pira, pepino, pimiento verde; leguminosas, chícharos, garbanzos,
caraotas; harinas y cereales, arroz, avena, harina de maíz de trigo; frutas,
frescas o secas. El organismo la digiere “de primero”. Tal vez por eso las
frutas es lo primero que siempre quieren comerse los niños. Otros grupos lo
conforman vegetales no verdes, zanahoria, papa, remolacha; oleaginoas y agua,
miel de abejas, yogourt, aguacate, frutos secos: almendras, maní, pistacho,
nueces en general.“Es frecuente que a nuestros niños los alimentemos solo con
cereal procesado y descuidemos otros alimentos como frutas, vegetales verdes y 
crudos, las verduras de tubérculos y de hojas, los granos, el pollo o pescado,
además si le sumamos un alto consumo de azúcar blanca y el deficiente ejercicio
físico, tendremos un caldo de cultivo para ansiedad infantil”.Natera resalta la
importancia de que los padres tomen conciencia del impacto que tiene cada
alimento en el sano desarrollo de sus hijo. Aparte de una dieta balanceada, la
actividad física es vital. Son muchos los estudios que se han llevado a cabo
para demostrar los beneficios del chocolate y cómo este incide en el estado
anímico. La razón es que el chocolate aumenta la dopamina y crea una sensación
de euforia. Además, la serotonina es otro neurotransmisor en el cerebro que
afecta directamente el estado de ánimo. Los niveles de carbohidratos en el
chocolate aumentan los aminoácidos en el torrente sanguíneo, que a su vez
estimulan la producción de triptófano que convierte a la
serotonina.Nutricionistas y nutrólogos insisten en que la clave de un día
enérgico está en el desayuno. Para que niños, jóvenes o adultos se mantengan
atentos, concentrados y de buen humor en sus clases, deben consumir una primera
comida cargada de nutrientes. La soya es un alimento beneficioso para numerosos
aspectos físicos y psíquicos de nuestro organismo. Es rica en triptófano e
incrementa también los niveles de serotonina en nuestro cerebro. Una arepa con
carne de soya es una alternativa.El té negro es una bebida efectiva contra el
estrés y para promover la relajación. Además de prevenir el cáncer, ayuda a
bajar de peso y apacigua la ansiedad. Aunque la reina de las infusiones es la
manzanilla, la lavanda tiene propiedades tranquilizantes. No solo es utilizada
en la cosmética, sino también para calmar el insomnio y la depresión. La
albahaca, aparte de usarse en la cocina, funciona para aplacar el sistema
nervioso: tres hojitas son suficientes para un buen té. En casos de mucha
ansiedad, una tacita proporcina calma.De la cantidad diaria recomendada de ácido
fólico se encuentra en una taza de lentejas. Además, contiene proteínas y
fibra.  Es uno de los alimentos que contribuye a mejorar el ánimo. Del grupo de
las leguminosas, estos granos son fuente de vitamina B, esencial para mejorar el
estado de ánimo y la función nerviosa en el cerebro junto al ácido fólico.

** La humedad desata los resfriados

[[http://www.eluniversal.com/noticias/estilo-vida/humedad-desata-los-resfriados_681363][La
humedad desata los resfriados]]

El más común de todos los males por los cambios bruscos de temperatura que se
producen en Navidad es el resfriado común. Esta infección se produce por un
virus en las vías respiratorias. Se contagia fácilmente de persona a persona y
no existen vacunas para prevenirlos.Para Luis Carlos Morillo, neumonólogo del
Centro Médico Docente La Trinidad, lo que afecta a las personas no es el frío,
sino la humedad que puede desencadenar enfermedades tales como el asma. "La gran
mayoría de los catarros en diciembre están motivados por infecciones virales,
que no llegan a ser gripes como tal", agrega el especialista. Las lluvias y las
bajas temperaturas incrementan la posibilidad de contagiarse de estas epidemias
a través de gotas de saliva que se transmiten mediante estornudos, tos o
simplemente hablando. En tal sentido, se calcula que aproximadamente el 90% de
todos los casos de resfriado común en Venezuela están producidos por algún tipo
de rinovirus. El catarro común afecta el tracto respiratorio superior, es decir,
bronquios, laringe, senos paranasales y faringe, sin perjudicar los pulmones.Los
síntomas incluyen estornudos frecuentes, secreción nasal, que puede ser
transparente al principio de la infección, alcanzan su intensidad entre el
primer y tercer día de evolución y tienen duración de siete a diez días, aunque,
ocasionalmente, pueden persistir hasta tres semanas. Morillo explicó que al
manifestarse otras señales tales como fiebre, escalofríos y malestar general, se
comenzaría a hablar de gripe, que es una patología diferente. Estos síntomas son
las respuestas que posee el organismo frente a los virus sin importar cual sea,
con la finalidad de que el cuerpo sea lo menos inhóspito para ellos. Por
ejemplo, la temperatura óptima para el rinovirus es 33-35 °C, por lo que no
soporta 38°C. Los adultos presentan resfriado común dos veces al año, mientras
que los niños pueden presentar el doble.El doctor Morillo recomienda a las
personas mantenerse lo suficientemente hidratadas. De igual forma, si el
individuo posee muchas secresiones, utilizar lavados nasales. Al mismo tiempo,
advirtió no utilizar antibióticos debido a que no están indicados por un
especialista; y a su vez, para prevenir un problema de salud pública.  Por otro
parte, aconseja a la población implementar los conceptos básicos de prevención.
Una buena limpieza de las manos tras estornudar, tirar los pañuelos desechables
a la papelera inmediatamente después de usarlos, y utilizar desinfectantes para
las zonas o áreas en las que se encuentre una persona con catarro, son los
medios más efectivos para prevenir el contagio.La pediatra, Claudia Cristina
Sánchez (@lactancia2.0 en Instagram), indica que los cambios bruscos de
temperatura también afecta a los niños, sobre todo a los menores de cinco años,
pues sus sistemas inmunitarios no están totalmente desarrollados. Aunque no se
pueden prevenir todos los catarros en el pequeño, sí se pueden reducir. En
primer lugar, las madres no deben dejar de alimentar a sus bebés con lactancia
materna, debido a que contiene los nutrientes necesarios para prevenir
enfermedades. Asimismo, evitar que los niños vayan al colegio si están enfermos,
por la sencilla razón de que están en contacto con otras personas; y por ende,
están expuestos a más gérmenes. Finalmente, lavarse las manos es crucial. La
higiene adecuada con agua y jabón, especialmente después de cambiar pañales y
antes de preparar la comida.

** Oferta de boletos es mínima en el aeropuerto de Maiquetía

[[http://www.eluniversal.com/noticias/caracas/oferta-boletos-minima-aeropuerto-maiquetia_681916][Oferta
de boletos es mínima en el aeropuerto de Maiquetía]]

En las terminales nacional e internacional del Aeropuerto Simón Bolívar de
Maiquetía, en el estado Vargas, los pasajeros que aún pueden comprar boletos
viven un calvario para llegar a su destino.  Quienes tienen sus boletos en mano
deben estar con tres horas de anticipación para abordar su vuelo en esta
Navidad.Desde hace dos semanas una gandola complicó aún más la situación para
los pasajeros que viajan por el aeropuerto. El vehículo de carga se llevó gran
parte del techo del túnel Boquerón II, sentido La Guaira - Caracas, lo que
provocó el cierre de esta vía y largas colas en ambos sentidos en la
autopista.Aún cuando las autoridades del Ministerio de Transporte respondieron
con celeridad ante el siniestro,  todavía continúan las labores de
rehabilitación en el lugar. La situación obligó  a implementar un canal de
contraflujo por el túnel lateral, para subir a Caracas o bajar al litoral
central.En la terminal nacional, las aerolíneas que operan con dos o tres
aviones hacia distintos estados del país ya no cuentan con boletos para esta
temporada navideña. Aún cuando los pasajes se venden entre Bs 542 mil y Bs 1
millón para Maracaibo, Lara y otros destinos.Solo en la línea Aerocaribe quedan
algunos boletos con destino al Zulia a Bs 904.700 ida y vuelta, por pocos días.
"Si lo compras solo de ida cuesta Bs 542 mil", informó el personal de guardia.En
Avior los operadores señalaron al público que no hay más boletería esta Navidad.
"Solo nos quedan vuelos a Bogotá y Panamá estas últimas dos semanas del año, a
precios desde Bs 17,5 millones hasta Bs 19 millones por boleto", dicen. En
líneas como Aserca, Láser y Estelar, el personal de guardia explicó a los
pasajeros que se agotaron los pocos boletos que tenían porque apenas tienen
operativos entre dos y tres aviones para tratar de cubrir la demanda nacional.
"Venga después del 15 de enero si desea ir a Lara, Maturín, Las Piedras y
Zulia", adelantaron.Ayer solo en la terminal nacional habían largas colas de
pasajeros. Sin embargo, en la internacional se observaron pocos viajeros con
destino a Panamá, Portugal, Miami y República Dominicana."En Laser puede venir a
finales de año a ver si se consigue algún boleto nacional. Rutaca, La
Venezolana, y Estelar están al tope", informaron voceros del  Instituto
Aeropuerto Internacional de Maiquetía (IAIM).Andrea Ramos, pasajera, relató en
la terminal internacional que bajó a la seis de la mañana, pero llegó dos horas
después a Maiquetía. "En Láser nos informaron que había retraso por los daños en
el túnel Boquerón II. Estaba dañado el techo del túnel con sentido a La Guaira y
las colas llegaban a Catia", afirmó.Muy pocos vuelos de Láser, Copa Airlines y
American salen cada semana por la terminal internacional, pues la falta de
repuestos y deudas del Estado mantienen a las aerolíneas operando con lo mínimo,
informaron operadores del servicio en Maiquetía. "Solo volamos dos veces al día.
A las 2:20 p.m., y a las 4:48 p.m.", informaron en American Airlines.Ayer los
pocos pasajeros que llegaban a Maiquetía por ambas terminales tardaron hasta dos
horas en tomar transporte superficial para ir a Caracas. "Está dañado el 80% de
las camionetas y taxis", informó Abel Santos, encargado del transporte
público.Maiquetía refleja, según los pasajeros y operadores de aerolíneas, la
crisis del país en todos los sentidos: hay pocos aviones operativos, poca oferta
de boletos, la vialidad está dañada y los espacios externos tienen poca
seguridad día y noche.Comerciantes, empaquetadores, carretilleros y demás
trabajadores precisaron que las ventas y atención diaria de clientes bajaron
hasta 75%. "Pocas personas tienen recursos para viajar y los que lo hacen no
vuelven", concluyeron.

** El buen cabello de ángel

[[http://www.eluniversal.com/noticias/suplementos/buen-cabello-angel_680492][El
buen cabello de ángel]]

Originaria de las tierras altas de México y de América Central, el cabello de
ángel (Cucurbita ficifolia) es una planta herbácea, parásita, conocida por su
fruto con el cual se prepara un exquisito y típico dulce fibroso característico
de la Navidad en Venezuela.De la familia cucurbitaceae también es conocido como
calabaza confitera, cidracayote, chilacayote, alcayota, alcayote, cayote,
chiverre, cidra, sambo, calabacito, pampanita y zapallo. Su nombre genérico de
origen latino significa calabaza y el específico ficifolia expresa hoja de
higo.El cabello de ángel se cultiva en las zonas altas con clima templado de
América, y también en África y Asia. En nuestro país se siembra mayormente en
los Andes. Si las condiciones son favorables, una misma planta puede dar hasta
50 frutos.Esta hierba perenne tiene tallos trepadores largos, ásperos y robustos
que pueden alcanzar hasta los 15 metros de largo y arroja una suerte de
zarcillos para trepar en la vegetación adyacente; las hojas son lobuladas y las
flores de color amarillo pálido.Los frutos son oblongos hasta casi globulares de
color verde con dibujos blancos o sólo blancos. La cáscara es dura, la pulpa es
jugosa, blanca y tan fibrosa que, después de cocida, se asemeja a una cabellera
enredada, y con ella se hace el dulce en almíbar conocido con el nombre de
cabellos de ángel. Puede tener hasta 500 semillas con forma aplanada y color
marrón o negro dependiendo de la variedad.Es una planta de grandes recursos, ya
que se pueden consumir sus hojas tiernas, las flores y el fruto.En algunas zonas
emplean esta herbácea como patrón para el injerto de plantas de melón.Unas
tajadas delgadas aplicadas durante 30 minutos sobre el rostro muy limpio sirven
como mascarilla humectante para la piel seca. Se enjuaga con agua fría. Con los
tallos, hojas y flores molidos en un mortero y mezclados con vaselina se prepara
una pomada antiséptica. Las cataplasmas se usan en las llagas y en los tumores
inflamados.El dulce de cabello de ángel con piña puede ser comido sin
consecuencias por los celíacos. Se asegura que durmiendo en colchones y con
almohadas rellenas de la planta y siguiendo un tratamiento con jugo de limón,
los reumáticos obtienen beneficios muy considerables. Su jugo regula la
temperatura cuando se tiene fiebre y sirve como diurético.   Las semillas se
consumen crudas o tostadas y son muy valoradas en la elaboración de dulces,
barras energéticas y granolas con alto contenido de fibra. Y son el ingrediente
principal de las palanquetas, un postre típico de la región mexicana de Chiapas.
Las flores, los brotes y el fruto verde pelado y hervido se utilizan como si
fueran verdura.500 gr de cabello de ángel3 huevos100 gr de queso blanco
rallado100 gr de azúcar100 gr de pan molido100 gr de leche en polvo125 gr de
canela en rama1 litro de agua1 panela de papelónLas cantidades necesarias
dePimienta negraPimienta blancaPimienta guayabitaAnís estrelladoLaurelTé verde
yyerbabuena Hielo seco&bullet; Cocine el cabello de ángel con medio litro de
agua por 40 minutos aproximadamente, luego procéselo en hilos y mézclelo con el
queso, la leche y el pan.&bullet; Después bata las yemas con el azúcar hasta
formar una crema y únala a la mezcla anterior. Bata las claras al punto de
nieve, y en forma envolvente añádala a la mezcla, y colóquela en un molde
engrasado y hornee.&bullet; Aparte, prepare el sirope con el papelón, agua y las
especias.&bullet; Haga una infusión con el té verde y la yerbabuena.&bullet;
Para el montaje debe tener dos envases:uno grande donde tiene que colocar la
infusión de té verde y yerbabuena y el hielo seco.Y uno más pequeño, el cual 
colocará arriba con el bizcocho bañado con el sirope y un merengue de cabello de
ángel.Este postre es ideal para acompañar la cena navideña.

** El éxito se trabaja

[[http://www.eluniversal.com/noticias/suplementos/exito-trabaja_680496][El éxito
se trabaja]]

—De la lectura estimulada por mis padres, Ana Rodríguez y Luis Benítez, y, más
adelante, por la necesidad de indagar por qué ocurrían hechos que me conmovían
profundamente.—A veces. Todo se mueve como se mueve el país. Si la conducción de
un país y su economía es un desastre, todo lo demás lo es, en consecuencia.A la
gente que cada día se levanta con la ilusión de hacer algo positivo por los
demás y por sí mismo. Es decir, a las personas que de lo ordinario hacen la vida
extraordinaria.—Lo conocí en el mundo librero; él es editor y fotógrafo. El
libro nos vinculó.—Fue una declaración expresada a dúo.—Mis vivencias en Cumaná,
mi lugar de nacencia, y sobre todo en la campiña del estado Sucre, aledaña a la
ciudad, donde  mi madre ejercía la docencia. Allí nació mi inmenso respeto y
amor hacia la naturaleza y sus habitantes.—La lectura, la música, los momentos
de soledad y de diálogo conmigo misma y con ÉL.—Si, muchas veces, si no la vida
no tendría sentido.—Por ahora, no. Venezuela necesita de todos los que podemos
hacer algo por ella.—No. Es parte de la vida.—Cuidadora y a la usanza de mi
madre; críe a mi hijo para que fuera un ser libre, autosuficiente, con valores,
con formación.——El desempeño profesional trae más ganancias que pérdidas,
independientemente de con quien lo realices. Toda experiencia profesional es
válida y el hecho de trabajar en familia es muy gratificante y exigente. Todos
vemos de cerca como crecen los proyectos y en que nos hemos equivocado. Nos hace
crecer como familia y como emprendedores.—Con el tiempo adquiere diferentes
matices y expresiones. Todo tiene su tiempo.—El que pierde la pasión, pierde la
posibilidad de estar vivo.—Comida alemana el 24 de diciembre y comida venezolana
el 31. Mucho vino y mucha música. Es un tiempo de felicidad, veo a mi familia,
mis amigos, mis afectos.Es la tercera de siete hermanos, su familia vive en el
extranjero y en varios estados venezolanos. Una vez al año se reúnen para
celebrar una Benitada. En estos 20 años se despidió con gran dolor de sus padres
y de su hermano mayor, Luis Ramón, cuando él tenía 53 años. Estuvo casada con el
poeta Alfredo Chacón, padre de OneChot.De pequeña soñó con ser bailarina y
actriz. Le gusta el olor a vainilla, la forma del infinito, el azul y “La rosa
púrpura de El Cairo” de Woody Allen. Cree que el éxito es alcanzar las metas que
se obtienen a través de la constancia, la organización y la planificación. Sus
intereses personales y profesionales están siempre ligados a las bellas artes.El
28 de febrero del 2012 enfrentó el mayor temor de una madre: perder a un hijo.
Juan David recibió un tiro en la frente durante un asalto. “Este miedo lo supero
cada día en su compañía”.Tiene una relación de pareja con Carsten Todtmann, con
quien trabaja en Oscar Todtmann Editores. Ella es la gerente editorial y él es
el presidente. Destaca que es una proeza establecer los límites para no mezclar
los roles ni las actividades. “El equilibrio se logra a través de una clara
comunicación y acuerdo. Después de la jornada profesional, a menos que sea una
emergencia, acordamos no abordar el tema trabajo”.

** Alertan que el país incumplió con pago a Cristallex

[[http://www.eluniversal.com/noticias/economia/alertan-que-pais-incumplio-con-pago-cristallex_681887][Alertan
que el país incumplió con pago a Cristallex]]

- Venezuela incumplió con el plazo para el pago de la primera cuota acordada con la empresa canadiense Crystallex, por una disputa sobre la expropiación de la mina de oro Las Cristinas, según documento citado por Redd Latam.El Gobierno acordó la cancelación de 441 millones de dólares con la minera canadiense Crystallex International con pagos mensuales de 40 millones de dólares este año y de 24 millones de dólares desde 2018 hasta 2020, de acuerdo con datos presentados en un caso de bancarrota canadiense, reseñó la agencia de noticias de mercados emergentes.Adicionalmente habrá más pagos a partir de 2020, pero no se conocieron los montos, indicó el texto. Redd Latam señaló que Venezuela no cumplió con el plazo para el pago de la primera cuota, de acuerdo con datos de Ernst & Young, supervisor nombrado por la corte del caso de bancarrota. Los informes fechados el 18 y 19 de diciembre revelan información previamente confidencial para cumplir con una solicitud del Juez Glenn A. Hainey de la Corte Superior de Justicia de Ontario.Venezuela acordó pagar 25 millones de dólares antes del 30 de noviembre, otros 15 millones de dólares a fines de este mes y 10 millones de dólares más antes de finales de enero de 2018, destacó el informe.“El primero de los pagos en Venezuela vencía el 30 de noviembre de 2017, pero no se recibió hasta la fecha de este informe”, dijo Ernst & Young en el informe del 18 de diciembre.Está programado que Crystallex comparezca esta semana en el Tribunal de Distrito de los Estados Unidos en Delaware en su intento de incautar acciones de PDV Holdings, propietaria de Citgo Holdings, que a su vez es propietaria de la compañía de refinación y oleoductos Citgo Petroleum.Crystallex exige las acciones alegando que Petróleos de Venezuela (Pdvsa) es un alter ego de la República. El abogado de la compañía canadiense, Jason Myatt, de Gibson Dunn, presentó una nueva declaración jurada para respaldar el reclamo del alter ego,  muestran registros judiciales.La transnacional minera canadiense ha dicho que el uso de Pdvsa por parte de Venezuela con fines de política.

** Trabajadores de la alcaldía Mayor denuncian que están en el limbo

[[http://www.eluniversal.com/noticias/caracas/trabajadores-alcaldia-mayor-denuncian-que-estan-limbo_681977][Trabajadores
de la alcaldía Mayor denuncian que están en el limbo]]

"La  decisión de la ANC de eliminar la alcaldía Metropolitana  coloca en un
limbo jurídico a todos los trabajadores de la Alcaldía Metropolitana y entes
asdcritos, cabildo y contraloría, dejando sin trabajo a seis mil personas",
afirmó Gustavo Rodríguez, secretario general del Sindicado de Empleados Públicos
Alcaldía Metropolitana de Caracas (Sumep-Alcamet). "Esta es la Navidad Feliz que
nos da el Gobierno Nacional a los empleados que a dos dias de Navidad no hemos
recibido el pago de aguinaldos", acóto.  Según detalló, se necesitan 20 mil
millones para pagar todas las deudas que tienen con los trabajadores, en
aumentos salariales desde julio a la fecha, primas, y bonos y aguinaldos, entre
otros beneficios. "Lo único que sabemos es lo que han declarado a la prensa que
van a nombrar una junta interventora para liquidar a los trabajadores, pero
todavía no sabemos quienes son porque no han llegado a las instalaciones",
aseveró el sindicalista.

** Sundde fiscalizó 6.721 empresas productoras de alimentos

[[http://www.eluniversal.com/noticias/economia/sundde-fiscalizo-6721-empresas-productoras-alimentos_682016][Sundde
fiscalizó 6.721 empresas productoras de alimentos]]

William Contreras, superintendente de Precios Justos, informó que se han
fiscalizado 6721 compañías productoras de alimentos.Agregó “La Superintendencia
Nacional para la Defensa de los Derechos Socioeconómicos ha hecho 7.860
procedimientos de los cuales 6.721 procedimientos de fiscalización están
asociados a empresas productoras de alimentos o comercialización de
alimentos”Añadió además que la idea “es proteger los derechos del pueblo en
cuanto al condicionamiento de venta, combatir la especulación, acaparamiento,
oferta engañosa,boicot y demás delitos económicos”, reseñó Unión RadioPor otro
lado, indicó que estos procedimientos  se efectuaron mayormente en estados donde
hay mayor cantidad de habitantes de acuerdo al Plan Navidades Felices

** Omar Minaya regresa a los Mets de Nueva York

[[http://www.eluniversal.com/noticias/mlb/omar-minaya-regresa-los-mets-nueva-york_682007][Omar
Minaya regresa a los Mets de Nueva York]]

Omar Minaya regresará a los Mets de Nueva York como asistente especial de Sandy
Alderson, quien lo reemplazó como gerente general del equipo después de la
temporada de 2010, reseñó AP. El dominicano fue asistente del gerente general de
los Mets entre 1997 y 2002, cuando se sumó a los Expos de Montreal como el
primer gerente general hispano en el béisbol. Regresó a los Mets como gerente
general tras la campaña de 2004, y ayudó a armar un equipo que disputó el
campeonato de la Liga Nacional en 2006. Fue despedido luego de dos temporadas
consecutivas con récord perdedor.  Minaya fue vicepresidente de los Padres de
San Diego entre 2011 y 2015, y desde entonces ha sido asesor del presidente del
sindicato de peloteros, Tony Clark. Minaya, de 59 años, trabajó como cazatalento
de Texas entre 1985-87.

** FIFA se considera una víctima en los casos de corrupción

[[http://www.eluniversal.com/noticias/futbol/fifa-considera-una-victima-los-casos-corrupcion_682021][FIFA
se considera una víctima en los casos de corrupción]]

La FIFA  anunció este viernes, a través de un portavoz, que se considera "una
víctima" de los casos por los que han sido hallados culpables de corrupción el
paraguayo Juan Ángel Napout y el brasileño José María Marín por una corte
federal de Nueva York. "Como el Departamento de Justicia de Estados Unidos ha
reconocido una vez más durante el juicio, la FIFA es víctima del presunto delito
que se ha tratado en el juicio", afirma un portavoz de la FIFA, destacó Efe. "La
FIFA apoya y anima firmemente los esfuerzos de las autoridades estadounidenses
para responsabilizar a las personas que abusaron de sus posiciones y
corrompieron el fútbol internacional para su propio beneficio personal",
agrega. Y concluye diciendo que "dado que el jurado ha declarado culpables a
varios acusados de los delitos imputados, la FIFA adoptará todas las medidas
necesarias para obtener la restitución y recuperar las pérdidas causadas por su
mala conducta". Los expresidentes del fútbol sudamericano, el paraguayo Juan
Ángel Napout y el brasileño José María Marín, fueron hallados culpables de
corrupción este viernes por una corte federal de Nueva York, en el sonado caso
conocido como "FIFA-Gate". Después de seis días de deliberaciones, un jurado de
la corte federal del distrito de Brooklyn declaró culpables al expresidente de
la Conmebol, Jose Ángel Napout y al que fuera mandatario de la Confederación
Brasileña de Fútbol, Jose María Marín, mientras que aún no ha alcanzado un
veredicto en el caso del ex máximo líder del fútbol en Perú, Manuel
Burga. Napout, Marín y Burga se habían declarado no culpables de las acusaciones
que presentó en su contra el Gobierno de Estados Unidos por corrupción y de
beneficiarse con la venta de los derechos televisivos de competiciones de la
FIFA como la Copa América.

** Economía venezolana se contrajo 16,1% en 2016

[[http://www.eluniversal.com/noticias/economia/economia-venezolana-contrajo-161-2016_681970][Economía
venezolana se contrajo 16,1% en 2016]]

- El Gobierno del presidente Nicolás Maduro presentó un informe ante la Comisión de Valores de Estados Unidos, en el cual se indica que  la economía venezolana se depreció un 16,2% en 2016, luego de una caída en 2015 del 6,2%.El informe detalla los datos oficiales más recientes sobre el desempeño del país petrolero, luego de que el Banco Central de Venezuela (BCV) dejara de divulgar información sobre los resultados de la economía de Venezuela en 2015, informó Reuters.El documento específica que la economía no petrolera se contrajo un 16,1%, lo que explica la recesión económica que vive la nación desde hace cuatro años aproximadamente.Con fecha del 21 de diciembre, los resultados del oficio indican que sectores como la construcción, que se hundió un 31,6%, y la actividad manufacturera que registró una caída del 27,1%, atribuyeron al déficit  de la actual economía del país. A su vez, el sector petrolero no se queda atrás, se redujo un 9,9% en 2016. El escrito muestra que la nación miembro de la Organización de Países Exportadores de Petróleo (OPEP) registró un déficit de 3.870 millones de dólares en la cuenta corriente de la balanza de pagos, notificó Reuters.Luego de recibir unos menguados ingresos petroleros, las importaciones del país también se redujeron 50,8% en el 2016 respecto al año anterior y se ubicaron en 16.370 millones de dólares. Por su parte, Venezuela registró una inflación de 274,4% que a comparación con  la del 2015 de 180,9%, se ubica entre las más altas del mundo, indican organismos multilaterales.Es preciso recordar nuevamente que, el BCV no ha divulgado información sobre la variación de precios desde 2015, lo que contribuye al desconocimiento absoluto de la data económica venezolana. Cabe destacar que la crisis económica que vive Venezuela en la actualidad ha golpeado con fuerza la capacidad de compra de los ciudadanos, debido a que los mismos, constantemente lidian con los altos precios y escasez de productos.

** Socialdemócratas alertan de un Gobierno en minoría en Alemania

[[http://www.eluniversal.com/noticias/internacional/socialdemocratas-alertan-gobierno-minoria-alemania_681944][Socialdemócratas
alertan de un Gobierno en minoría en Alemania]]

El vicecanciller alemán, el socialdemócrata Sigmar Gabriel, alertó de los
posibles efectos negativos de un Gobierno en minoría en Alemania, en una
entrevista con el grupo mediático germano Funke. En el Partido Socialdemócrata
alemán (SPD) hay voces importantes que ven como una alternativa posible este
tipo de Gobierno, declaró el ministro de Exteriores en funciones. , apuntó,
reseñó DPA.Tras el fracaso en noviembre de las negociaciones de los
conservadores de la canciller Angela Merkel con los ecologistas y liberales, los
socialdemócratas se han convertido ahora en el partido llamado a formar un
Gobierno de coalición con los conservadores, como ya hicieran en la pasada
legislatura, en un intento por evitar la convocatoria de nuevas elecciones en la
mayor economía de Europa. A principios del 2018, el SPD se reunirá con los
conservadores en la ronda preliminar de contactos de tendrá lugar hasta el 12 de
enero. En ese momento,  o si dan el proceso por fracasado, profundizando en la
crisis de formación de Gobierno abierta tras las elecciones generales del pasado
24 de septiembre.  Los conservadores hablarán con el SPD sobre "los
contratiempos en los hospitales y en las residencias", pero también sobre las
mejoras para las familias y niños, la ampliación de la banda ancha, mejorar la
cualificación para las nuevas profesiones y sobre el camino hacia el pleno
empleo, explicó Altmaier.

** Abbas dice que palestinos rechazarán mediación de EEUU en proceso paz

[[http://www.eluniversal.com/noticias/internacional/abbas-dice-que-palestinos-rechazaran-mediacion-eeuu-proceso-paz_681942][Abbas
dice que palestinos rechazarán mediación de EEUU en proceso paz]]

El presidente de la Autoridad Nacional Palestina (ANP), Mahmud Abbas, aseguró
hoy que los palestinos rechazarán cualquier papel de Estados Unidos en los
esfuerzos de paz con Isreal.   en un comunicado un días después de que la
Asamblea General de la ONU votara ampliamente en contra de reconocer Jerusalén
como capital de Israel. "Estados Unidos decidió apoyar las reivindicaciones y
retórica de Israel de una 'capital judía' exclusiva, por encima de la inclusión
y el respeto que debería tener una ciudad importante para las tres religiones
monoteístas", dijo en un comunicado antes de Navidad.Al término del encuentro
entre ambos, el mandatario francés dijo que Estados Unidos se había
marginalizado a sí mismo en el conflicto palestino-israelí.  Macron señaló
además que en este momento también está en contra de un reconocimiento
unilateral de Palestina como Estado soberano. "Eso sería una respuesta a otra
decisión unilateral que ha provocado agitación en la región".  Durante su
campaña electoral, Trump aseguró que iba a forjar un acuerdo de paz entre
israelíes y palestinos. Estados Unidos ha acabado aislado en su iniciativa sobre
Jerusalén.En tanto,  antes de la votación.  "Es tipo de chantaje suponen un
golpe al carácter de instituciones como la ONU, que constituyen la columna
vertebral del sistema internacional", dijo hoy Erdogan en Ankara. Estados Unidos
advirtió antes de la votación que iba a tomar nota de quienes votaban en contra
y amenazó con recortar ayudas a los países que así lo hicieran.  Aliados
tradicionales de Washington como Reino Unido y Francia votaron en contra de la
iniciativa de Trump. , pero Israel reivindica toda la ciudad como capital
indivisible. Israel ocupó la parte este de la ciudad en la Guerra de los Seis
días, en 1967.

** Diseñan guante que traduce lenguaje de señas para sordomudos

[[http://www.eluniversal.com/noticias/estilo-vida/disenan-guante-que-traduce-lenguaje-senas-para-sordomudos_682002][Diseñan
guante que traduce lenguaje de señas para sordomudos]]

.- Con el objetivo de crear escenarios inclusivos para las personas con
discapacidad del habla y auditiva, un estudiante mexicano diseñó un guante que
identifica los movimientos de la mano y los reproduce en texto o audio, informó
Efe. "La persona sordomuda podrá hacer las señas correspondientes al lenguaje de
señas y el guante identificará los movimientos, generará la letra o palabra
asociada a la seña y así las personas que no conozcan el lenguaje de señas
entenderán el mensaje", dijo el estudiante Bryan Howard Tarre Álvarez. El
guante, llamado "Intelligent talking hand", fue diseñado por el alumno de la
carrera de ingeniería electromecánica de la Universidad Autónoma de Querétaro,
con el cual se hizo acreedor al primer lugar del reto de Salud pública en el
concurso Vive conCiencia 2017. Según la Encuesta Nacional de la Dinámica
Demográfica 2014, elaborada por el Instituto Nacional de Estadística y Geografía
(INEGI), un 18 % de las personas con alguna discapacidad tienen dificultad para
hablar o comunicarse. Tarre Álvarez explicó que el proyecto incorpora un
algoritmo de inteligencia artificial conocido como "redes neuronales". "Estas
redes son un modelo matemático en el cual a través de un algoritmo de
actualización y entrenamiento es capaz de aprender a reconocer patrones como lo
hacemos los humanos", expuso el estudiante. Intelligent talking hand funciona
con sensores flexo-resistivos, es decir, transductores que convierten una
flexión (ángulo) del material en una variación de resistencia. Es así que, al
doblar un dedo se genera un cambio en la resistencia que a su vez produce una
variación de voltaje. El cambio en el voltaje puede ser leído por un convertidor
analógico-digital y procesado por un microcontrolador. Aunque el proyecto aún
está en desarrollo, Tarre Álvarez detalló que están cerca de terminar el
algoritmo y solamente faltaría complementar la base de datos. "Tenemos pensado
donar 10 guantes a instituciones que atiendan a sordomudos para calibrar la
biomecánica, es decir, la velocidad, fuerza, curvatura, posición exacta de cada
dedo, que cambia con la anatomía de cada persona", dijo el estudiante. Del mismo
modo, aseguró que aunque existen ya guantes que forman palabras y frases a
través de señas, "no tienen el toque de inteligencia artificial". Tarre Álvarez
señaló en un año cuando el proyecto puede estar terminado, ya como un producto
funcional.

** Fusión de dos estrellas de neutrones, el descubrimiento científico del año

[[http://www.eluniversal.com/noticias/estilo-vida/fusion-dos-estrellas-neutrones-descubrimiento-cientifico-del-ano_682008][Fusión
de dos estrellas de neutrones, el descubrimiento científico del año]]

La revista "Science" divulgó hoy su lista de los diez grandes descubrimientos
científicos de 2017, que lidera la observación por primera vez en la historia de
la fusión de dos estrellas de neutrones a través de sus ondas
gravitacionales. Este avistamiento, que abrió una nueva era en la astrofísica,
tuvo lugar el pasado 17 de agosto, cuando diversos telescopios, localizados en
varios puntos de la Tierra, tomaron imágenes de la fusión de dos estrellas de
neutrones, fenómeno llamado kilonovas. Las estrellas que implosionaron giraban
una alrededor de la otra en la constelación Hidra, a 130 millones de años luz de
la Tierra. Las existencia de las ondas gravitacionales la predijo a inicios del
siglo pasado Albert Einstein, pero su detección no se produjo hasta 2015, un
hecho que ha sido distinguido este año con el Premio Nobel de Física, reseñó
Efe. En la lista de grandes avances científicos de 2017 figura también el
desarrollo de la criomicroscopía electrónica, que le valió este el Nobel de
Química al suizo Jacques Dubochet, al germano-estadounidense Joachim Frank y al
británico Richard Henderson. Se trata de un método efectivo "para generar
imágenes tridimensionales de las moléculas de la vida", con lo que se ha logrado
comprender mejor enfermedades como el cáncer o alzhéimer. Otro descubrimiento
que destaca "Science" es la creación de un detector portátil de unas partículas
subatómicas llamadas neutrinos. Es obra de un equipo internacional de
científicos que consiguió confirmar una predicción sobre los neutrinos hecha
hace casi medio siglo, mediante el experimento COHERENT desarrollado en el
Laboratorio Nacional Oak Ridge en Estados Unidos. La reputada revista menciona
igualmente el hallazgo de los restos más antiguos conocidos del "Homo sapiens",
datados entre hace 300.000 y 350.000 años, que se encontraron en el yacimiento
arqueológico Yebel Irhoud (Marruecos), a unos 150 kilómetros al oeste de
Marrakech. Esto supone un cambio de 100.000 años respecto a los restos más
antiguos encontrados hasta ahora, que tenían alrededor de 195.000 años de
antigüedad y que fueron hallados en Etiopía. En la lista de la publicación
estadounidense sobresale el desarrollo de dos técnicas relacionadas con la
herramienta de edición genética CRISPR: una se dirige al ácido de ribonucleico
(ARN), sin modificar el genoma de manera permanente, y la otra desarrolla un
nuevo "editor de bases". Otro logro que valora "Science" es el impulso que tomó
este año la plataforma de publicación de artículos científicos preliminares en
el terreno de la Biología, bioRxiv, que se lanzó hace cuatro años pero que en
2017 recibió el apoyo de organizaciones de EE.UU. y el Reino Unido. También
entra en la clasificación la decisión de la Administración de Alimentos y
Medicamentos (FDA) de EE.UU. de aprobar un nuevo tratamiento (de nombre
comercial Kymriah) contra la leucemia que es la primera terapia génica contra el
cáncer que se autoriza en el país. El descubrimiento en Sumatra (Indonesia) de
un nuevo tipo de orangután hasta ahora desconocido se incluye, asimismo, entre
los grandes avances científicos de 2017. Bautizado como "Pongo tapanuliensis",
fue hallado por investigadores de la Universidad de Zúrich (Suiza) y de dos
instituciones españolas: el Instituto de Biología Evolutiva (IBE-CSIC) y el
Centro de Regulación Genómica (CNAG-CRG) La extracción de hielo antártico
congelado hace 2,7 millones de años en la zona de Allan Hills por parte de
expertos de las universidades de Princeton y Maine, en EE.UU., se hace un hueco
también en la lista de "Science". Esa muestra es 1,7 millones de años más
antigua que cualquier otra extraída anteriormente. Por último, la revista
incluye un trabajo del Nationwide Children's Hospital en Columbus (EE.UU.) y la
compañía Avexis con terapia génica, cuyos científicos pudieron salvar la vida de
bebés que nacieron con una enfermedad neuromuscular al agregar un gen que
faltaba en sus neuronas espinales.

** Los pasaportes británicos serán azules tras el Brexit

[[http://www.eluniversal.com/noticias/internacional/los-pasaportes-britanicos-seran-azules-tras-brexit_681940][Los
pasaportes británicos serán azules tras el Brexit]]

Los pasaportes británicos volverán a tener la cubierta azul después de que el
Reino Unido salga de la Unión Europea (UE) en 2019, informó hoy el Ministerio de
Interior. El nuevo diseño, que no incluirá la insignia de la UE, reemplazará la
actual cubierta de color borgoña, utilizada desde los pasados años ochenta,
reseñó Efe.El secretario de Estado de Interior, Brandon Lewis, dijo hoy que los
nuevos pasaportes serán muy seguros al adoptar la más alta tecnología para
evitar que sean falsificados. "Dejar la UE nos da la oportunidad única de
restablecer nuestra identidad nacional y forjar un nuevo camino para nosotros en
el mundo", señaló Lewis al dar a conocer esta noticia. "Es por ello que estoy
encantado de anunciar que los pasaportes británicos volverán a su icónico diseño
en color azul y dorado una vez que hayamos dejado la Unión Europea en 2019",
agregó. Los nuevos pasaportes serán emitidos por etapas una vez que el país
abandone el bloque europeo en marzo de 2019. El azul fue el primer color que
apareció en el pasaporte británico en 1921, pero el diseño cambió en 1988
después de que el Reino Unido se unió a la entonces Comunidad Económica Europea
(CEE).

** Cicpc ultima a hombre que había asesinado a su novia

[[http://www.eluniversal.com/noticias/sucesos/cicpc-ultima-hombre-que-habia-asesinado-novia_681993][Cicpc
ultima a hombre que había asesinado a su novia]]

A Isbeth de Jesús Medina Jiménez, de 18 años, la encontraron muerta cerca del
mediodía de este jueves dentro de un pozo séptico en el patio de una vivienda
del barrio Campo Unido II, en la avenida Intercomunal del municipio Cabimas,
estado Zulia. Estaba desaparecida desde hacía cinco días. Su pareja la había
asesinado.Dos horas después de su hallazgo, el sujeto resultó abatido al
enfrentarse a comisiones del Cuerpo de Investigaciones Científicas, Penales y
Criminalísticas (Cicpc) que lo buscaban en la misma ciudad de la Costa Oriental
del Lago.La noche del sábado 16 de diciembre, la joven salió de su casa junto a
su novio Adonis Yonaiker Chirinos Hernández, de 18 años. Irían a una fiesta
junto a un grupo de amigos. El domingo en la tarde, Isbeth aún no había
regresado a su casa. Sus padres empezaron a llamar al joven y a otros amigos. A
través de las redes sociales publicaron su foto con números de contacto, en caso
de conocerse su paradero.No fue sino hasta la mañana de este jueves cuando el
hedor de un cuerpo en avanzado estado de descomposición de Isbeth alertó a los
vecinos que localizaron el cuerpo en el interior de un pozo séptico.En el patio
de la casa de Adonis, su pareja de varios meses, hallaron el cadáver de la
fémina con signos de heridas por arma blanca.Tras el hallazgo los funcionarios
se activaron en la zona para buscar al joven. Lo encontraron en una residencia
de la calle Rosario, sector Villanueva en Cabimas.Al llegar los detectives no se
quiso entregar a las autoridades y se enfrentó con un arma calibre 38. Tras
resultar herido lo trasladaron hasta el ambulatorio donde ingresó muerto.

** Gremios médicos de Nueva Esparta critican indiferencia ante crisis de salud

[[http://www.eluniversal.com/noticias/venezuela/gremios-medicos-nueva-esparta-critican-indiferencia-ante-crisis-salud_681951][Gremios
médicos de Nueva Esparta critican indiferencia ante crisis de salud]]

Representantes del Colegio de Médicos de Nueva Esparta, de la Sociedad Médicos
Especialistas y de la Sociedad Venezolana de Pediatría en la región insular se
pronunciaron nuevamente sobre la crisis del sector salud, y, en el marco de un
mensaje de fin de año, llamaron a las autoridades a la reflexión.En nombre del
gremio, Franklin Cortez, presidente de la Sociedad de Médicos Especialistas del
Hospital Luis Ortega de Porlamar, dijo que es preocupante la postura indiferente
que han mostrado hasta ahora las autoridades de salud locales y nacionales,
frente a lo que consideran ha sido la mayor crisis sanitaria que ha vivido el
estado Nueva Esparta y Venezuela.Cortez detalló todas las acciones que durante
el año realizaron para que se corrigieran situaciones, incluso como gremio,
declararon la salud y al hospital en emergencia, pero todo siempre fue en
vano.Recordó igualmente que hicieron una colecta pública de medicamentos para
ayudar a las personas hospitalizadas, entregaron en el hospital central un
documento donde expusieron las fallas de dotación, mantenimiento preventivo de
equipos así como las carencias a nivel de modelos académicos en los postgrado,
fueron suspendidas las intervenciones electivas por falta de insumos y
medicamentos, pero nunca fue atendida la escasez, y la conclusión es que la
crisis en los centros asistenciales sigue igual.  En tal sentido hicieron
llamado a las autoridades a  rectificar  y a atender la situación de crisis que
vive la red hospitalaria y ambulatoria en las islas de Margarita y Coche, para
frenar la incidencia de patologías.“En todos los casos hemos hecho propuestas de
soluciones tanto a nivel intrahospitalario como a nivel regional, y hasta la
fecha no han obtenido respuesta alguna, por eso ante un nuevo año que no
advierte mejores situaciones para el país, nos  a la orden del nuevo gobernador
Alfredo Díaz, a fin de ofrecerle asesoría para la implementación de verdaderas
políticas de salud ajustadas a la realidad de la comunidad neoespartana”,
propusieron los especialistas.

** Trancaron vías en sectores de Maturín por falta de comida y gas

[[http://www.eluniversal.com/noticias/venezuela/trancaron-vias-sectores-maturin-por-falta-comida-gas_682004][Trancaron
vías en sectores de Maturín por falta de comida y gas]]

Vecinos del complejo habitacional La Gran Victoria, ubicado en la parroquia Los
Godos de Maturín, cerraron la redoma que conduce al sector conocido como Los
Iraníes exigiendo comida y la recolección inmediata de la basura.Desde las 6:30
de la mañana de este viernes, obstruyeron el paso tras cinco meses de retraso en
las cajas de los Comités Locales de Abastecimiento y Producción (CLAP), pese a
que la gran mayoría de sus residentes son afectos al oficialismo.Más tarde, a
las 10:30 am habitantes de San Judas Tadeo, La Chicharronera y Rosa Inés
trancaron la avenida Raúl Leoni a la altura del parque Andrés Eloy Blanco en la
vía al sur de Maturín, porque llevan una semana tratando de comprar el gas
doméstico.Ricardo Cabello, habitante de Santa Inés, rechazó que desde hace cinco
días no reciben los cilindros con gas en el centro de acopio desde donde se
distribuye el servicio a un precio promedio de Bs. 4 mil por bombona. "Llevamos
una semana levantándonos a las 3:00 am para hacer la cola pero el gas no llega.
Ya hoy es 22 de diciembre y no podemos pasar la Navidad sin poder cocinar el
poco alimento que conseguimos".Benito Pérez, habitante de San Judas Tadeo,
agregó que los tíckets del bono navideño no fueron distribuidos en la comunidad,
un beneficio que esperaban con ansias pero que nunca llegó para quienes
realmente los necesitan.

** Falta de efectivo genera desesperación entre los trujillanos

[[http://www.eluniversal.com/noticias/venezuela/falta-efectivo-genera-desesperacion-entre-los-trujillanos_682028][Falta
de efectivo genera desesperación entre los trujillanos]]

En el estado Trujillo la falta de efectivo ha puesto a más de uno a dar carreras
en esta época decembrina, muchos deben hacer largas colas en los bancos varias
veces a la semana para obtener dinero y así poder realizar las acostumbradas
compras navideñas.Ante esta situación,Otros ciudadanos recurren al trueque de
alimentos o servicios y a las transferencias bancarias para conseguir los
alimentos con lo que les alcanza el salario o las pensiones que reciben.Pese a
que el Gobierno nacional, en su intento de frenar la escasez de circulante y
controlar la inflación, emitió un nuevo cono monetario a principios de este año,
a los ciudadanos cada vez se les hace más cuesta arriba tener dinero en efectivo
a la mano, por lo que algunos se ven en la necesidad de pagar un porcentaje para
obtener billetes.“No tengo dinero en efectivo ni para el pasaje”, expresó Mercy
Chacón, residente del municipio San Rafael de Carvajal, quien refutó que limiten
a los usuarios el acceso de dinero.Largas colas, desesperación y rabia se
observan en los bancos y cajeros automáticos de la ciudad de Valera, puesto que
las personas rechazan las limitaciones al momento de retirar su dinero.En
algunas entidades bancarias sólo entregan 10 mil bolívares por cajero y Bs. 20
mil por taquilla, cantidades insuficientes para diligenciar asuntos diariamente,
sobre todo si se trata de personas que deben movilizarse de un municipio a
otro.Finalmente, Renny Pimentel, otro de los entrevistados, exigió al Gobierno
nacional tomar medidas en contra de los acaparadores de dinero. "Sin dinero
¿cómo me movilizo?", agregó. Al mismo tiempo, reclamó que en los bancos
únicamente tienen prioridades con los pensionados, lo que a su juicio perjudica
a los ahorristas que no pueden disponer de su dinero.

** Presuntos colectivos matan a atracador en Quinta Crespo

[[http://www.eluniversal.com/noticias/sucesos/presuntos-colectivos-matan-atracador-quinta-crespo_682012][Presuntos
colectivos matan a atracador en Quinta Crespo]]

Presuntos integrantes de grupos armados que hacen vida en el área de Quinta
Crespo, dieron muerte de múltiples impactos de bala a un sujeto quien habría
sido capturado en momentos en que asaltaba a una persona.El hombre ultimado fue
identificado como Yerson Antonio Cacúa (35), quien recibió cinco disparos entre
pecho y cara, presuntamente propinados por miembros de los grupos armados que lo
capturaron en las inmediaciones de la esquina de RCTV en Bárcenas.Cacúa era
originario del estado Carabobo, donde dejó a sus tres hijos de 12, 10 y 9
años.Su padre Antonio Cacúa señaló “bastante le dije a ese muchacho que se
viniera a la casa, que dejara las malas compañías con las que se la pasaba,
ahora está muerto, es el segundo hijo que entierro este año, al primero me lo
mataron a inicios de año, era un Guardia Nacional y lo mataron para robarlo”.

** Bancos solo dan Bs 20 mil y bachaqueros quitan 70% por el papel moneda

[[http://www.eluniversal.com/noticias/venezuela/bancos-solo-dan-mil-bachaqueros-quitan-por-papel-moneda_681902][Bancos
solo dan Bs 20 mil y bachaqueros quitan 70% por el papel moneda]]

En la región se acentúa la falta de efectivo a solo dos días para la Nochebuena,
y aunque hay familias que intentan viajar, es un suplicio pagar el pasaje con
billetes.Los bancos del Estado solo ofrecen 20 mil bolívares, y en los privados
a veces deben esperar en cola a que lleguen depositantes para ofrecerles los
mismos 20 mil bolívares. Los avances de efectivo están prohibidos en la región
por órdenes del gobernador Víctor Clark, sin embargo, a través de las redes
sociales los ofrecen al 55, 60 y hasta 70% de comisión.Carlos Semeco, refirió
que hay tiendas donde los productos que se pagan con billetes son un poco más
baratos, mientras que en otros simplemente no aceptan débito. “La gente cree que
es fácil, uno pasa un día en un banco para tener 20 mil bolívares y eso no
alcanza ni para comprar un kilo de arroz. Creo que adoptan medidas para ellos
poder bachaquear el efectivo”.En un recorrido por la terminal de Punto Fijo, los
viajeros pedían al Gobierno estipular una medida de pago del pasaje de manera
electrónica debido a que es muy difícil costear los viajes con dinero en
efectivo.Pablo Arenas, refirió que vive en Punto Fijo y cada cierto tiempo viaja
a San Cristóbal. “Este viaje cada vez es más difícil, aquí la cosa está muy
difícil para conseguir efectivo y en ninguna terminal hay punto de venta por que
a según y que están dañados, eso deberían investigarlo”, dijo.

** Partidos de la MUD mantendrán pacto para directiva de la AN

[[http://www.eluniversal.com/noticias/politica/partidos-mud-mantendran-pacto-para-directiva_681854][Partidos
de la MUD mantendrán pacto para directiva de la AN]]

La Asamblea Nacional (AN) contará con una nueva directiva el próximo año según
el acuerdo rotativo establecido dentro de la Mesa de la Unidad Democrática
(MUD); en concordancia, la presidencia le corresponderá a Un Nuevo Tiempo (UNT),
la primera vicepresidencia a Avanzada Progresista (AP) y la segunda a Primero
Justicia (PJ), mientras que la Secretaría le corresponde a Acción Democrática
(AD).No obstante, persisten dudas sobre la permanencia del pacto entre los
integrantes de la mayoría opositora en el Parlamento, y sobre el papel que le
corresponderá cumplir a la AN en el año que está por iniciarse, ya que permanece
el desconocimiento de sus competencias constitucionales.El Universal conversó
con varios parlamentarios y dirigentes políticos, sobre si debe respetarse dicho
convenio en vista de los recientes cambios que ha sufrido el ámbito legislativo
y político en el país, así como cuál debe ser la orientación institucional del
Parlamento en el 2018.En su mayoría coincidieron que debe ser honrado y tomado
como una base para un futuro acuerdo de gobierno nacional, mientras que
dirigentes de la nueva fracción “16 de Julio” (16J) consideran que el acuerdo
debe ser revisado y evaluar qué directiva le conviene más al país.A continuación
las diversas respuestas de los legisladores:-Si, claro debemos mantener el
acuerdo. Como representación del pueblo, la AN debe continuar en el marco de la
defensa de la Constitución y las competencias del Parlamento para salir de la
crisis.El próximo año debemos asumir el liderazgo de acompañamiento a un pueblo
que está padeciendo una terrible crisis; nuestra actuación como un poder público
debe estar concentrado en ayudar a la construcción de una salida política a la
crisis.-Si, no existe una razón por la cual no debamos mantener el pacto, que
puede hasta fusionarnos como una base para un futuro acuerdo de gobernabilidad
en el país.Como progresistas damos prioridad a la problemática social y desde la
AN vamos a exigir al Gobierno que atienda la crisis que existe en el país.-La
MUD no existe está muerta y sepultada, de igual manera que ese acuerdo que
establece que el próximo año UNT asuma la Presidencia. A mi juicio tendría que
ser revisado, nadie que esté en este momento planteando levantarle las sanciones
a los corruptos del Gobierno puede llegar a ser presidente del Parlamento, sería
un desastre para la oposición.En los primeros días de enero debemos reunirnos
para crear un debate abierto que escoja una directiva que le convenga al
país.-La Asamblea está funcionando bajo un esquema de rotación con respeto a su
directiva y secretaria, el reto que tiene con esta nueva junta es estructurar
una nueva estrategia para salir de la incertidumbre en que se encuentra frente a
la decisión del Tribunal Supremo de Justicia (TSJ), el cual impide la ejecución
de las acciones contra el gobierno debido a que ha declarado un desacato.-El
pacto creció bajo la base de la MUD, como ya no existe no podemos hablar de un
pacto, sin embargo quien presente su credencial y cuente con los votos puede
pertenecer a la directiva. Nosotros estamos evaluando si se va a respetar el
pacto.Debemos rescatar la AN porque no estamos en desacato, tenemos que hacer
respetar los postulados que eligieron los venezolanos el 16 de julio.-Es
importante preservar todo aquello que formó parte de la estructura de la Unidad,
dentro de ese concepto general mantener el pacto de gobernabilidad es clave. El
2018 será mas complejo, el papel de la AN es fundamental para conectar la
racionalidad entre los políticos y la sociedad, para ello, la nueva directiva
será crucial.

** Vicente Díaz acusó a la ANC de "ilegalizar" partidos políticos

[[http://www.eluniversal.com/noticias/politica/vicente-diaz-acuso-anc-ilegalizar-partidos-politicos_681931][Vicente Díaz acusó a la ANC de "ilegalizar" partidos políticos]]

El exrector del Consejo Nacional Electoral (CNE), Vicente Díaz,
condenó el   (ANC) el pasado miércoles.“Ilegalizar partidos por ejercer su
derecho de decidir en cuál elección participan, es una aberración jurídica y
democrática (&mldr;)”, escribió Díaz a través de un tuit.El decreto –aprobado
por el suprapoder que preside Delcy Rodríguez– obliga a las organizaciones
políticas a validarse nuevamente para unos próximos comicios si estas no
participaron en el evento electoral inmediatamente anterior.La medida, según el
extitular del ente electoral, “(...) en nada contribuye a la seguridad jurídica
indispensable para generar inversiones que saquen al país de este desastre
económico”.A través de un , Voluntad Popular (VP), Acción Democrática (AD) y
Primero Justicia (PJ) anunciaron que las últimas decisiones de la ANC –como el
decreto sobre la validación de partidos políticos– serán denunciadas en el
proceso de diálogo entre Gobierno y oposición previsto para los días 11 y 12 de
enero en República Dominicana.

** Grandes sismos en 2017

[[http://www.eluniversal.com/infografias/universal-canales/grandes-sismos-2017_532840][Grandes sismos en 2017]]



** Los hitos políticos de Venezuela que marcaron el año 2017

[[http://www.eluniversal.com/noticias/politica/los-hitos-politicos-venezuela-que-marcaron-ano-2017_681603][Los hitos políticos de Venezuela que marcaron el año 2017]]

En Venezuela se vivieron diversos hechos políticos de repercusión internacional.
La dinámica de tales situaciones trajo como consecuencia separaciones de algunos
grupos políticos, agresiones contra funcionarios, protestas antigubernamentales
que marcaron la historia reciente de la nación.Conforme el tiempo pasa y en
vísperas del cierre del turbulento año 2017, se presentan, de manera
cronológica,.Para iniciar este recorrido debemos dar un paso al 2016, cuando las
fuerzas de la oposición al gobierno de Nicolás Maduro decidieron convocar un
Referendo Revocatorio, consagrado en el artículo 72 de la Constitución de la
República Bolivariana de Venezuela, el cual establece que los cargos de elección
popular, como la presidencia de la República, son revocables una vez que haya
transcurrido la mitad del periodo de tiempo determinado en la misma Carta Magna.
Asimismo, indica que un número no menor al 20 por ciento de los electores
inscritos en el registro del Poder Electoral, puede solicitar la convocatoria a
un referendo popular con la intención de revocar del cargo al funcionario en
cuestión.A pesar de la aparente “facilidad” con la que que se presenta en el
texto constitucional la realización de esta convocatoria popular,Es así que el
llamado para recabar las firmas del 1% de los electores, con el fin de solicitar
luego las firmas del 20% del Registro Electoral, no se pudo realizar debido a
que entes del Gobierno nacional acusaron a la oposición de hacer fraude mientras
se recogía la primera tanda de rúbricas. Ante ello, los tribunales penales de
los estados Trujillo, Aragua, Bolívar, Carabobo, Monagas, Apure y Zulia (sin
competencia para decidir en este tipo de casos) anularon la recolección del 20%,
lo que causó que la fecha para realizar el Referendo Revocatorio antes del 10 de
enero del 2017, no pudiera concretarse. Cabe destacar que la Mesa de la Unidad
Democrática (MUD) tenía la esperanza de convocar a dichas elecciones antes de
esta fecha, pues esa iba a ser la única manera de revocar al presidente Nicolás
Maduro. De no ser así y si se realizaba en el primer trimestre del 2017 (tal
como lo estipuló el CNE), y de ganar la oposición quedaría el vicepresidente de
la República en el cargo, quien en ese momento era Aristóbulo Istúriz. Las En
vista de ello y en búsqueda de otras alternativas, el 9 de enero del 2017, el
Parlamento venezolano declara el abandono del cargo de Nicolás Maduro, debido a
que había faltado al cumplimiento de sus funciones. El diputado Henry Ramos
Allup manifestó, en su momento que “el Gobierno de Nicolás Maduro es totalmente
fallido y forajido. El abandono de cargo es la forma de resolver la crisis. Se
abandona cuando no se cumple debidamente con las funciones correspondientes”.A
pesar de la declaratoria de la Asamblea Nacional (AN), esta decisión no se
ejecutó. En tal sentido, eDada la crisis del país, la oposición comenzó a
fijarse en otras opciones para salir deponer al Gobierno, pero la lucha de
poderes entre la AN, electa el 6 de diciembre del 2015, y el TSJ se intensificó.
El 28 de marzo del 2017, la Sala Constitucional, que desde el 24 de febrero
estaba en manos del magistrado Maikel Moreno,La sentencia 155 estableció, en un
primer lugar, que , debido a que la AN había establecido un “Acuerdo sobre la
Reactivación del Proceso de Aplicación de la Carta Interamericana de la OEA,
como mecanismo de resolución pacífica de conflictos para restituir el orden
constitucional en Venezuela”, y que fue rechazado por el diputado oficialista,
Héctor Rodríguez, quien interpuso un recurso de nulidad al máximo tribunal el 22
de marzo del 2017. Con esta sentencia, también se dejó en evidencia que el TSJ
limitó la inmunidad parlamentaria de los diputados del Parlamento.  La sentencia
156, por su parte,  “para velar por el Estado de Derecho”, dejando sin efecto a
la Asamblea Nacional y la voluntad de los electores que sufragaron en diciembre
de 2015.El 31 de marzo, Luisa Ortega Díaz, quien estaba a cargo de la Fiscalía
General de la República, denunció que dichos dictámenes del máximo tribunal de
Venezuela representaban una “ruptura del hilo constitucional”. Igualmente, la
oposición, países extranjeros y la Organización de Estados Americanos (OEA),
calificaron la acción del TSJ como un “autogolpe” perpetrado por Maduro y sus
seguidores. El 1 de abril del 2017, la misma Sala Constitucional del TSJ
dictaminó en contra de sus propias decisiones en las sentencias 157 y 158
respectivamente, pero ya se había iniciado un movimiento de protestas ciudadanas
que reclamaba en Desde el 1 de abril, las protestas se extendieron en todo el
territorio nacional.  En se periodo la MUD llamó a hacer marchas, trancas, paros
generales y demás acciones públicas de manera sistemática que tuvieron efecto
internacional.En el marco de las protestas que sacudían a Venezuela y debido a
las constantes denuncias por parte de la OEA contra el gobierno de Nicolás
Maduro, el 26 de abril el presidente de la República, en la voz de la entonces
canciller Delcy Rodríguez, decidió retirar al país de la organización con la
intención de “acabar con los abusos intervencionistas”. Esto fue, igualmente,
mal visto por la comunidad internacional, expectante por las manifestaciones que
se desarrollaban en la nación.El 1 de mayo, Maduro convoca a una  con la
intención de apaciguar las protestas que se seguían desarrollando en esos días.
“Convoco a una Constituyente profundamente Obrera, Comunal, del Pueblo”,
sentenció el mandatario desde un acto para conmemorar el Día del Trabajador, en
la avenida Bolívar de Caracas. Horas después hizo entrega de las bases de la
convocatoria al CNE. Fue el 23 de ese mes cuando el Poder Electoral anunció que
las elecciones para elegir a los constituyentistas se realizarían el 30 de
julio.Cuando las protestas tendían a decaer, el 27 de junio un ataque contra el
Tribunal Supremo de Justicia desde un helicóptero, en manos del comisario del
Cuerpo de Investigaciones Científicas, Penales y Criminalísticas (Cicpc), Óscar
Pérez, acentuó el alto grado de incertidumbre que se vivía en el país. Otro día
de gran relevancia para Venezuela fue el 8 de julio, fecha en la que el TSJ
concedió “casa por cárcel” a Leopoldo López, quien estaba recluido en la
penitenciaria militar de Ramo Verde, en Los Teques, estado Miranda. El líder
opositor apresado en febrero del 2014, El 16 de julio se efectuó la consulta
popular impulsada por la oposición, en donde sufragaron, según la MUD, , quienes
expresaron su rechazo a la ANC, así como solicitaron la obediencia de la Fuerza
Armada Nacional Bolivariana (FANB) para defender la Constitución del año 1999 y
la completa renovación de cada uno de los Poderes Públicos.Pero el 30 de julio,
tal como lo indicó el CNE, se llevaron a cabo los comicios de la Asamblea
Nacional Constituyente, donde, según el Poder Electoral, .Por otra parte, el 1
de agosto, un día después de las elecciones de la ANC, los opositores Leopoldo
López y Antonio Ledezma fueron sacados de sus residencias, donde cumplían la
condena de “casa por cárcel”, debido a videos que difundieron a través de
sus redes sociales. El de López fue difundido el 26 de julio, días antes de las
elecciones de la ANC, y se refirió a la protestas como una herramienta necesaria
para la “libertad”.Ledezma, por su parte, difundió el video el 31 de julio, un
día después de los comicios solicitados por Maduro, en el que señaló que “los
poderes públicos se han puesto al servicio de una tiranía que el domingo
reincidió en seguir golpeando, destruyendo nuestro Estado de Derecho, apoyándose
en siete magistrados de naturaleza ilegal y en una fracción de la Fuerza Armada
Nacional”. Asimismo, el exalcalde Metropolitano, se refirió a la Asamblea
Nacional Constituyente como "un fraude".Ambos dirigentes fueron regresados a sus
casas el día 4 del mismo mes, Tarek William Saab fue designado como el nuevo
Fiscal General de la República por la Asamblea Nacional Constituyente el 5 de
agosto, . Cabe destacar que fue el constituyentista Diosdado Cabello quien lo
propuso como el nuevo fiscal. Al respecto, Saab indicó, en su momento, que se
encargaría de hacer cumplir "el mandato que esta magna Asamblea Nacional
Constituyente me ha encomendado hacer"."Hacer justicia con dignidad, con decoro,
para todos, de manera equilibrada, dándole un mensaje al mundo de que esta es
una democracia firme que respeta los derechos humanos pero con dignidad y con
honor", sentenció el fiscal designado en esa oportunidad.La madrugada del 6 de
agosto el país se enteró de un alzamiento militar en el Fuerte Paramacay,
ubicado en Naguanagua, estado Carabobo, donde efectivos del Ejército se
declararon en rebelión en contra del presidente Nicolás Maduro. En este suceso
hubo un enfrentamiento que causó la muerte de una persona, así como funcionarios
heridos. pero el capitán Juan Caguaripano, se atribuyó el asalto en un video que
colgó en redes sociales.Un mes relativamente tranquilo fue septiembre donde se
destacó el día 4, pues la ANC comenzó la discusión de la Ley contra el Odio y la
Intolerancia por la Convivencia Pacífica. En octubre 15 se celebraron las
elecciones regionales, , donde resultaron electos 17 gobernadores para el
Partido Socialista Unido de Venezuela (PSUV) y cinco por la oposición. Cabe
destacar que la MUD no aceptó los resultados porque, a juicio de la
organización, éstos presentaron irregularidades y lo mismo hizo la AN, pero el
19 de octubre.Cabe destacar que una de las condiciones era que los gobernadores
tenían que juramentarse ante la ANC y el 23 de octubre, los cuatro mandatarios
regionales representados por el partido político Acción Democrática (AD),
Antonio Barreto, Alfredo Díaz, Laidy Gómez y Ramón Guevara se presentaron ante
la institución en el Palacio Federal Legislativo. Por su parte, el gobernador
electo del Zulia (Primero Justicia), Juan Pablo Guanipa, se negó a “rendirse”
frente a la ANC, El día 3 de noviembre, la Sala Plena del Tribunal Supremo de
Justicia inhabilitó la inmunidad parlamentaria del diputado Freddy Guevara, una
de las figuras opositoras que dirigió las protestas que se realizaron en abril.
Este dictamen luego fue remitido a la Asamblea Nacional Constituyente para
solicitar la apertura de un juicio en contra del parlamentario.El 5 de noviembre
la embajada de Chile en Venezuela concedió el asilo para Guevara en calidad de
huésped y luego el 6, la ANC aprobó el juicio en contra del diputado, quien fue
acusado por los delitos de flagrancia, asociación para delinquir, instigación
pública continuada y uso de adolescentes para delinquir.El exalcalde
Metropolitano, Antonio Ledezma, causó un gran revuelo en el país el 17 de
noviembre,  Estuvo apresado en su hogar desde el año 2016, debido a que fue
acusado por los delitos de conspiración y asociación para delinquir.El 10 de
diciembre se celebraron las elecciones municipales, , así como los comicios
regionales en el Zulia, dada la falta absoluta del gobernador electo el 15 de
octubre. En este evento electoral, el PSUV salió victorioso con la gran mayoría
de los ayuntamientos (más de 300) y la gobernación de ese estado.En el mes de
diciembre han ocurrido hechos de gran importancia: el 1 de diciembre,  con la
finalidad de llegar a acuerdos concretos que buscaran la estabilidad del país;
sin embargo, fue pospuesto para el día 15 del mismo mes.Tanto el gobierno como
la oposición acordaron discutir seis puntos, con el objetivo de llegar a
acuerdos que permitieran la paz y la solución de la crisis en el país.Los puntos
en las conversaciones fueron los siguientes:- Apertura de un canal humanitario
que facilite medicinas y comida a los venezolanos que más lo necesitan.-
Reestructuración completa del Consejo Nacional Electoral para poder ir a
elecciones libres y garantizadas.- Liberación de todos los "presos políticos”.-
Reconocimiento y restitución de cada uno de los poderes parlamentarios
inherentes a la Asamblea Nacional.- Reconocimiento internacional de la Asamblea
Nacional Constituyente.- Levantamiento de sanciones económicas que pesan sobre
algunos funcionarios del Gobierno nacional.Y al llegar el día 15 de diciembre,
tal como se estableció a principio del mes, las delegaciones de ambas fuerzas
políticas se encontraron en República Dominicana para una segunda reunión que
buscó, igualmente, soluciones efectivas para la crisis que atraviesa el país, a
través de la discusión de los seis puntos destacados. Sin embargo, nuevamente no
se llegó a acuerdo alguno, por lo que el Gobierno y la oposición Recientemente,
específicamente el pasado 20 de diciembre de 2017, la ANC suprimió y eliminó las
alcaldías metropolitanas de Caracas y la del Alto Apure, creadas durante el
Gobierno del fallecido presidente Hugo Chávez.Al respecto, el artículo 172 de la
Constitución señala que “(&mldr;) cuando los Municipios que deseen constituirse
en un distrito metropolitano pertenezcan a entidades federales distintas,
corresponderá a la Asamblea Nacional su creación y organización”.Otra de las
medidas tomadas por la ANC, en la sesión del día 20 fue la de exigir a los
partidos políticos que no participaron en las pasadas elecciones regionales a
renovarse ante el Consejo Nacional Electoral (CNE), al margen de lo previsto en
la Ley Orgánica de Procesos Electorales que contempla que una organización
política se invalida cuando no participa en dos comicios consecutivos de
carácter nacional.

** Los nuevos billetes

[[http://www.eluniversal.com/infografias/economia/los-nuevos-billetes_480131][Los nuevos billetes]]



** Cancillería denunció encuentro de EEUU y Canadá para hablar sobre Venezuela

[[http://www.eluniversal.com/noticias/politica/cancilleria-denuncio-encuentro-eeuu-canada-para-hablar-sobre-venezuela_681929][Cancillería denunció encuentro de EEUU y Canadá para hablar sobre Venezuela]]

La Cancillería venezolana denunció este jueves que el encuentro del pasado 19 de
diciembre de los ministros de Relaciones Exteriores de Estados Unidos y Canadá
con el fin de tomar “acciones contra" Venezuela es una “nueva amenaza contra su
paz y soberanía”.  A través de un comunicado publicado en su página web, el
Ministerio para las Relaciones Exteriores señaló que ambos países se reunieron
en Ottawa con el fin, entre otras cosas, de hablar de Venezuela, prometiendo,
según la ministra de Canadá, Chrystia Freeland, tomar “acciones” contra el país
de manera individual, en conjunto o con la cooperación de un grupo de “gobiernos
subordinados a los EEUU” agrupados en el llamado Grupo de Lima.“Esta nueva
amenaza está orientada a socavar el proceso de diálogo que se desarrolla en
República Dominicana, donde el Gobierno Bolivariano y la oposición han avanzado
en aspectos importantes para garantizar la estabilidad política y económica del
país”, señaló el texto.Además, la Cancillería rechaza “estas amenazas y
cualquier tipo de acción que estos gobiernos dirijan para continuar o ampliar el
ilegal bloqueo económico y desestabilizar la paz y el sosiego del pueblo
venezolano”.

** Panorama en cifras de los crímenes en protestas

[[http://www.eluniversal.com/infografias/sucesos/panorama-cifras-los-crimenes-protestas_518330][Panorama en cifras de los crímenes en protestas]]



** En El Cafetal se organizan para brindar transporte a los electores

[[http://www.eluniversal.com/audios/politica/cafetal-organizan-para-brindar-transporte-los-electores_536543][En El Cafetal se organizan para brindar transporte a los electores]]



** Entrevista Andrea Roa

[[http://www.eluniversal.com/audios/universal-canales/entrevista-andrea-roa_526998][Entrevista Andrea Roa]]



