#+TITLE: Make static site with hugo 
#+STARTUP: overview
#+AUTHOR: xing wenjuIRC: linuxing3 on freenode
#+EMAIL: xingwenju@gmail.com

---

* Define writer layers

  Basic Setting

#+begin_src emacs-lisp
(defconst xingwenju-writer-packages
  '(
    ox-hugo
    easy-hugo
    )
  )

(defun xingwenju-writer/init-easy-hugo ()
  "Start hugo support and load library"
  (use-package easy-hugo
    :ensure t
    :init
    (setq easy-hugo-basedir "~/Dropbox/xingwenju.com/hugo/")
    (setq easy-hugo-url "https://linuxing3.github.io")
    (setq easy-hugo-sshdomain "mini")
    (setq easy-hugo-root "/home/blog/")
    (setq easy-hugo-default-ext ".org")
    (setq easy-hugo-previewtime "300"))
  )

(defun xingwenju-writer/init-ox-hugo ()
  "Start hugo support and load library"
  (use-package ox-hugo
    :ensure t 
    :after ox)
    ;; (load-library "ox-hugo")
  )
#+end_src


* Follow elections

** Heading

 Los venezolanos comenzaron a votar este domingo en un proceso que avizora un
 nuevo triunfo para Nicolás Maduro, último ensayo antes de los comicios de 2018
 en los que el mandatario planea optar a la reelección.

 Con la crisis económica golpeando cada vez más fuerte, el escepticismo marca la
 jornada en la que serán escogidos 335 alcaldes para un período de cuatro años
 entre 1.568 candidatos.

 Unos 14.000 centros de votación comenzaron a activarse a partir de las 6:00 am.
 Un par de horas después, la vicepresidenta del Consejo Nacional Electoral (CNE),
 Sandra Oblitas, dijo a la prensa que “80% de las mesas” estaban constituidas.

 El oficialismo gobierna actualmente 242 municipios y la oposición 76. Los demás
 son administrados por disidentes o independientes.

 Rostro del desánimo

 Víctor Torres, conductor en la ciudad de Maracaibo (noroeste), cree que votando
 no resuelve su mayor dolor de cabeza: la hiperinflación, con precios escalando
 2.000% este año, según analistas.

 “El otro día fui a comprar un plátano: en la mañana costaba 1.900 bolívares y en
 la tarde 3.000. Es imposible vivir así. Estoy decepcionado de los políticos”,
 dijo Torres. Aun si quisiera votar, no puede pagar el transporte por la escasez
 de efectivo.

 Tras un aumento de 30% hace un mes, el ingreso mínimo apenas alcanza para tres
 kilos de carne, en medio de una aguda escasez de alimentos, medicinas e insumos.

 Vía libre

 Maduro tiene el camino despejado luego de que los tres partidos que dominan la
 coalición Mesa de la Unidad Democrática (MUD) rechazaran participar.

 Las agrupaciones de Henrique Capriles, Leopoldo López -en arresto domiciliario-
 y Henry Ramos Allup se marginaron tras denunciar irregularidades en las
 elecciones del 15 de octubre, en las que el chavismo ganó 18 de 23
 gobernaciones.

 Pero otros movimientos y dirigentes compiten por cuenta propia, agravando las
 fracturas en una oposición que en las pasadas elecciones movilizó a dos millones
 de personas menos que en 2015, cuando arrasó en las legislativas.

 “El gobierno ni siquiera va a hacer la misma trampa de las regionales. Yendo
 divididos no lo necesita”, declaró Yon Goicoechea, aspirante a dirigir un
 municipio capitalino, contrariando a López, su líder.

 Expertos electorales como Eugenio Martínez ven “inviable” que la oposición pueda
 mantener siquiera la mitad de sus alcaldías por las deserciones y la “presión de
 la maquinaria chavista”, y prevén que el gobernante Partido Socialista Unido de
 Venezuela (PSUV) “mejorará sus cuotas de poder”.

 “Será una victoria casi segura del gobierno, con alta abstención”, señaló el
 politólogo Luis Salamanca.

 Luis Vicente León, presidente de la encuestadora Datanálisis, advierte de un
 “escenario demoledor” para la oposición, pues “ni habrá una abstención masiva”
 que deslegitime el proceso, “ni un triunfo relevante” de quienes compiten.

 Las municipales no suelen tener gran convocatoria en el país con las mayores
 reservas petroleras. En 2013 la participación fue de 42%.

 Presidenciales a la vista

 La MUD se enfoca en las presidenciales, previstas para fines de 2018, pero que
 según líderes opositores y analistas podrían ser adelantadas al primer
 trimestre.

 Garantizar “condiciones justas” es su prioridad en las negociaciones emprendidas
 con el gobierno la semana pasada, que también dividen a la MUD.

 “A veces hay que sacrificar un peón para ir por la reina”, justificó el diputado
 Freddy Guevara. Su copartidario Goicoehecha lo contradice: “Si frustramos más a
 la gente, si confundimos más al electorado, en las presidenciales ganará Maduro,
 no porque hiciera trampa, sino por incapacidad para conducir la mayoría que
 somos”.

 Maduro, en tanto, tiene del desafío de ampliar una base electoral estancada,
 aunque bien aceitada con “clientelismo”, apunta Salamanca.

 Tras sortear protestas que buscaban su salida y dejaron unos 125 muertos entre
 abril y julio, el mandatario -apoyado por los militares- logró elegir una
 Asamblea Constituyente que rige con poderes absolutos, integrada solo por
 oficialistas.

 Desconocido por varios gobiernos, este órgano amplió el vasto poder
 institucional de Maduro, cuya aprobación subió de 24,4% a 31,1%, según una
 encuesta de la firma Venebarómetro realizada entre octubre y noviembre.

 La evaluación negativa de la MUD, en cambio, aumentó de 46,1% a 65,7%. “Tenemos
 que continuar con la revolución para no perder las ayudas que nos llegan. Por
 eso voto y apoyo la reelección de Maduro”, declaró Edie Mesa, de 55 años, líder
 comunal de la favela de Petare, beneficiario de mercados subsidiados que vende
 el gobierno para paliar el desabastecimiento.


** Gobierno
 Jorge Rodríguez, ministro de Comunicación e Información, señaló que el 100% de
 las mesas en todo el país se encuentran instaladas.

 Rodríguez manifestó que los votantes que tengan el carnet de la patria se deben
 presentar en los puntos tricolor para que los verifiquen."Todo nuestro pueblo
 con lealtad y con la mirada puesta en el futuro, que se lleve su carnet de la
 patria, es muy importante que se lea en las afueras de los centros de votación
 el código QR", dijo.

 El ministro de Comunicación explicó que la verificación es una manera de
 detectar y determinar el despliegue de los electores. Destacó que es la tercera
 elección que se realiza este año luego de la constituyente y las regionales.

** EE.UU

 La Embajada de Estados Unidos en Venezuela emitió una serie de mensajes con
 motivo de las elecciones municipales de este domingo.

 A través de su cuenta de Twitter, la Embajada indicó que “el gobierno de
 Venezuela debe estar determinado por sus ciudadanos, quienes tienen derecho a
 participar libremente y en paz”.

 El ente diplomático también manifestó que la comunidad internacional insta al
 gobierno a respetar los derechos y escogencias de los venezolanos.

 Este domingo se escogen a los 335 alcaldes de las distintas localidades del país
 por un periodo constitucional de cuatro años.
