name: deploy hugo on gh pages

on:
  push:
    branches:
      main

jobs:
  build-hugo-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: main
          submodules: true
      - name: Deploy public to main
        uses: linuxing3/gh-action-hugo-deploy@master
        with:
          destination_repo: linuxing3/linuxing3.github.io
          destination_token: ${{ secrets.DEPLOY_TOKEN }}
          build_dir: "public"